name:                haal
version:             0.1.0.0
github:              "steve-anunknown/haal"
license:             BSD-3-Clause
author:              "Stefanos Anagnostou"
maintainer:          "steve.anunknown@gmail.com"
copyright:           "2025 Stefanos Anagnostou"

extra-source-files:
- README.md 
extra-doc-files:
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/steve-anunknown/haal#readme>
synopsis:            "A Haskell library for Active Automata Learning."
category:            "Model Learning"

dependencies:
- base >= 4.18.3 && < 4.21

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - containers >= 0.6 && < 0.7
    - mtl >= 2.3.1 && < 2.4
    - random >= 1.2.1 && < 1.2.2
    - vector >= 0.13.1 && < 0.13.2

tests:
  haal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haal
    - hspec
    - containers >= 0.6 && < 0.7
    - QuickCheck
    - mtl >= 2.3.1 && < 2.4
    - random >= 1.2.1 && < 1.2.2

executables:
  div:
    main: div.hs 
    source-dirs: examples
    dependencies: 
    - haal 
    - base
    - mtl >= 2.3.1 && < 2.4
  demo: 
    main: demo.hs 
    source-dirs: examples
    dependencies: 
    - haal 
    - base
    - containers >= 0.6 && < 0.7
  io:
    main: io.hs 
    source-dirs: examples
    dependencies: 
    - haal 
    - base
    - process >= 1.6.19 && < 1.6.25
    - mtl >= 2.3.1 && < 2.4
  website:
    main: website.hs 
    source-dirs: examples
    dependencies: 
    - haal 
    - base
    - process >= 1.6.19 && < 1.6.25

