name:                haal
version:             0.1.0.0
github:              "steve-anunknown/haal"
license:             BSD-3-Clause
author:              "Stefanos Anagnostou"
maintainer:          "steve.anunknown@gmail.com"
copyright:           "2025 Stefanos Anagnostou"

extra-source-files:
- README.md 
extra-doc-files:
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/steve-anunknown/haal#readme>
synopsis:            "A Haskell library for Active Automata Learning."
category:            "Model Learning"

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - containers >= 0.6.7 && < 0.7
    - mtl >= 2.2.2 && <= 2.3.1
    - random

tests:
  haal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haal
    - hspec
    - containers
    - QuickCheck
    - mtl
