-- Generated by haal-gen. Do not edit manually.
module Haal.Models.TLS.GnuTLSV3V3V12ServerRegular
    ( GnuTLSV3V3V12ServerRegularInput (..)
    , GnuTLSV3V3V12ServerRegularOutput (..)
    , gnuTLSV3V3V12ServerRegular
    ) where

import Haal.Automaton.MealyAutomaton (MealyAutomaton, mkMealyAutomatonTable)

data GnuTLSV3V3V12ServerRegularInput
    = In_ApplicationData
    | In_ApplicationDataEmpty
    | In_ChangeCipherSpec
    | In_ClientHelloRSA
    | In_ClientKeyExchange
    | In_EmptyCertificate
    | In_Finished
    | In_HeartbeatRequest
    deriving (Show, Eq, Ord, Enum, Bounded)

data GnuTLSV3V3V12ServerRegularOutput
    = Out_Alert_Fatal__Unexpected_message____ConnectionClosed
    | Out_Empty
    | Out_ServerHello_Certificate___CertificateRequest___ServerHelloDone
    | Out_ChangeCipherSpec___Finished
    | Out_Alert_Fatal__Internal_error____ConnectionClosed
    | Out_ApplicationData___Alert_Warning__Close_notify____ConnectionClosed
    | Out_Alert_Warning__Close_notify____ConnectionClosed
    | Out_Alert_Fatal__Handshake_failure____ConnectionClosed
    | Out_HeartbeatResponse
    | Out_ConnectionClosed
    deriving (Show, Eq, Ord, Enum, Bounded)

{- Transitions (state  input -> next state / output):
    0     In_ApplicationData       -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_ApplicationDataEmpty  -> 0 / Out_Empty
          In_ChangeCipherSpec      -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_ClientHelloRSA        -> 2 / Out_ServerHello_Certificate___CertificateRequest___ServerHelloDone
          In_ClientKeyExchange     -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_EmptyCertificate      -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_Finished              -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_HeartbeatRequest      -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
    1     In_ApplicationData       -> 1 / Out_ConnectionClosed
          In_ApplicationDataEmpty  -> 1 / Out_ConnectionClosed
          In_ChangeCipherSpec      -> 1 / Out_ConnectionClosed
          In_ClientHelloRSA        -> 1 / Out_ConnectionClosed
          In_ClientKeyExchange     -> 1 / Out_ConnectionClosed
          In_EmptyCertificate      -> 1 / Out_ConnectionClosed
          In_Finished              -> 1 / Out_ConnectionClosed
          In_HeartbeatRequest      -> 1 / Out_ConnectionClosed
    2     In_ApplicationData       -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_ApplicationDataEmpty  -> 2 / Out_Empty
          In_ChangeCipherSpec      -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_ClientHelloRSA        -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_ClientKeyExchange     -> 6 / Out_Empty
          In_EmptyCertificate      -> 5 / Out_Empty
          In_Finished              -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_HeartbeatRequest      -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
    3     In_ApplicationData       -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_ApplicationDataEmpty  -> 3 / Out_Empty
          In_ChangeCipherSpec      -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_ClientHelloRSA        -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_ClientKeyExchange     -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_EmptyCertificate      -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_Finished              -> 4 / Out_ChangeCipherSpec___Finished
          In_HeartbeatRequest      -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
    4     In_ApplicationData       -> 1 / Out_ApplicationData___Alert_Warning__Close_notify____ConnectionClosed
          In_ApplicationDataEmpty  -> 4 / Out_Empty
          In_ChangeCipherSpec      -> 1 / Out_Alert_Warning__Close_notify____ConnectionClosed
          In_ClientHelloRSA        -> 1 / Out_Alert_Fatal__Handshake_failure____ConnectionClosed
          In_ClientKeyExchange     -> 1 / Out_Alert_Warning__Close_notify____ConnectionClosed
          In_EmptyCertificate      -> 1 / Out_Alert_Warning__Close_notify____ConnectionClosed
          In_Finished              -> 1 / Out_Alert_Warning__Close_notify____ConnectionClosed
          In_HeartbeatRequest      -> 4 / Out_HeartbeatResponse
    5     In_ApplicationData       -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_ApplicationDataEmpty  -> 5 / Out_Empty
          In_ChangeCipherSpec      -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_ClientHelloRSA        -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_ClientKeyExchange     -> 6 / Out_Empty
          In_EmptyCertificate      -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_Finished              -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_HeartbeatRequest      -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
    6     In_ApplicationData       -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_ApplicationDataEmpty  -> 6 / Out_Empty
          In_ChangeCipherSpec      -> 3 / Out_Empty
          In_ClientHelloRSA        -> 1 / Out_Alert_Fatal__Internal_error____ConnectionClosed
          In_ClientKeyExchange     -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_EmptyCertificate      -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_Finished              -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
          In_HeartbeatRequest      -> 1 / Out_Alert_Fatal__Unexpected_message____ConnectionClosed
-}
gnuTLSV3V3V12ServerRegular :: MealyAutomaton Int GnuTLSV3V3V12ServerRegularInput GnuTLSV3V3V12ServerRegularOutput
gnuTLSV3V3V12ServerRegular =
    case mkMealyAutomatonTable 7 0 deltaTable lambdaTable of
        Right m -> m
        Left err -> error ("haal-gen: invalid transition table: " ++ err)
  where
    deltaTable =
        "\1\0\1\2\1\1\1\1\
        \\1\1\1\1\1\1\1\1\
        \\1\2\1\1\6\5\1\1\
        \\1\3\1\1\1\1\4\1\
        \\1\4\1\1\1\1\1\4\
        \\1\5\1\1\6\1\1\1\
        \\1\6\3\1\1\1\1\1"
    lambdaTable =
        "\0\1\0\2\0\0\0\0\
        \\9\9\9\9\9\9\9\9\
        \\0\1\0\0\1\1\0\0\
        \\0\1\0\0\0\0\3\0\
        \\5\1\6\7\6\6\6\8\
        \\0\1\0\0\1\0\0\0\
        \\0\1\1\4\0\0\0\0"
