-- Generated by haal-gen. Do not edit manually.
module Haal.Models.DTLS.GnutlsV3V5V19PskRsaCertNreq
    ( GnutlsV3V5V19PskRsaCertNreqInput (..)
    , GnutlsV3V5V19PskRsaCertNreqOutput (..)
    , gnutlsV3V5V19PskRsaCertNreq
    ) where

import Haal.Automaton.MealyAutomaton (MealyAutomaton, mkMealyAutomatonTable)

data GnutlsV3V5V19PskRsaCertNreqInput
    = In_RSA_CLIENT_HELLO
    | In_RSA_CLIENT_KEY_EXCHANGE
    | In_PSK_CLIENT_HELLO
    | In_PSK_CLIENT_KEY_EXCHANGE
    | In_CHANGE_CIPHER_SPEC
    | In_FINISHED
    | In_APPLICATION
    | In_CERTIFICATE
    | In_EMPTY_CERTIFICATE
    | In_CERTIFICATE_VERIFY
    | In_Alert_WARNING_CLOSE_NOTIFY
    | In_Alert_FATAL_UNEXPECTED_MESSAGE
    deriving (Show, Eq, Ord, Enum, Bounded)

data GnutlsV3V5V19PskRsaCertNreqOutput
    = Out_HELLO_VERIFY_REQUEST
    | Out_SERVER_HELLO_CERTIFICATE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
    | Out_SERVER_HELLO_SERVER_HELLO_DONE
    | Out_TIMEOUT
    | Out_CHANGE_CIPHER_SPEC_FINISHED
    | Out_APPLICATION
    deriving (Show, Eq, Ord, Enum, Bounded)

{- Transitions (state  input -> next state / output):
    0     In_RSA_CLIENT_HELLO                -> 1 / Out_HELLO_VERIFY_REQUEST
          In_RSA_CLIENT_KEY_EXCHANGE         -> 1 / Out_HELLO_VERIFY_REQUEST
          In_PSK_CLIENT_HELLO                -> 1 / Out_HELLO_VERIFY_REQUEST
          In_PSK_CLIENT_KEY_EXCHANGE         -> 1 / Out_HELLO_VERIFY_REQUEST
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_HELLO_VERIFY_REQUEST
          In_FINISHED                        -> 1 / Out_HELLO_VERIFY_REQUEST
          In_APPLICATION                     -> 1 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE                     -> 1 / Out_HELLO_VERIFY_REQUEST
          In_EMPTY_CERTIFICATE               -> 1 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE_VERIFY              -> 1 / Out_HELLO_VERIFY_REQUEST
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_HELLO_VERIFY_REQUEST
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_HELLO_VERIFY_REQUEST
    1     In_RSA_CLIENT_HELLO                -> 3 / Out_SERVER_HELLO_CERTIFICATE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
          In_RSA_CLIENT_KEY_EXCHANGE         -> 1 / Out_HELLO_VERIFY_REQUEST
          In_PSK_CLIENT_HELLO                -> 4 / Out_SERVER_HELLO_SERVER_HELLO_DONE
          In_PSK_CLIENT_KEY_EXCHANGE         -> 1 / Out_HELLO_VERIFY_REQUEST
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_HELLO_VERIFY_REQUEST
          In_FINISHED                        -> 1 / Out_HELLO_VERIFY_REQUEST
          In_APPLICATION                     -> 1 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE                     -> 1 / Out_HELLO_VERIFY_REQUEST
          In_EMPTY_CERTIFICATE               -> 1 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE_VERIFY              -> 1 / Out_HELLO_VERIFY_REQUEST
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_HELLO_VERIFY_REQUEST
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_HELLO_VERIFY_REQUEST
    2     In_RSA_CLIENT_HELLO                -> 5 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 2 / Out_HELLO_VERIFY_REQUEST
          In_PSK_CLIENT_HELLO                -> 5 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 2 / Out_HELLO_VERIFY_REQUEST
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_HELLO_VERIFY_REQUEST
          In_FINISHED                        -> 2 / Out_HELLO_VERIFY_REQUEST
          In_APPLICATION                     -> 2 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE                     -> 2 / Out_HELLO_VERIFY_REQUEST
          In_EMPTY_CERTIFICATE               -> 2 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE_VERIFY              -> 2 / Out_HELLO_VERIFY_REQUEST
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_HELLO_VERIFY_REQUEST
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_HELLO_VERIFY_REQUEST
    3     In_RSA_CLIENT_HELLO                -> 6 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 7 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 6 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 8 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 6 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 9 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 10 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 6 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 6 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 6 / Out_TIMEOUT
    4     In_RSA_CLIENT_HELLO                -> 6 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 11 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 6 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 15 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 6 / Out_TIMEOUT
          In_APPLICATION                     -> 4 / Out_TIMEOUT
          In_CERTIFICATE                     -> 6 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 6 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 6 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 6 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 6 / Out_TIMEOUT
    5     In_RSA_CLIENT_HELLO                -> 5 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 5 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 5 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 5 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 5 / Out_TIMEOUT
          In_APPLICATION                     -> 5 / Out_TIMEOUT
          In_CERTIFICATE                     -> 5 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 5 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 5 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 5 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 5 / Out_TIMEOUT
    6     In_RSA_CLIENT_HELLO                -> 3 / Out_SERVER_HELLO_CERTIFICATE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
          In_RSA_CLIENT_KEY_EXCHANGE         -> 11 / Out_HELLO_VERIFY_REQUEST
          In_PSK_CLIENT_HELLO                -> 4 / Out_SERVER_HELLO_SERVER_HELLO_DONE
          In_PSK_CLIENT_KEY_EXCHANGE         -> 11 / Out_HELLO_VERIFY_REQUEST
          In_CHANGE_CIPHER_SPEC              -> 12 / Out_HELLO_VERIFY_REQUEST
          In_FINISHED                        -> 6 / Out_HELLO_VERIFY_REQUEST
          In_APPLICATION                     -> 6 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE                     -> 6 / Out_HELLO_VERIFY_REQUEST
          In_EMPTY_CERTIFICATE               -> 6 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE_VERIFY              -> 6 / Out_HELLO_VERIFY_REQUEST
          In_Alert_WARNING_CLOSE_NOTIFY      -> 6 / Out_HELLO_VERIFY_REQUEST
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 6 / Out_HELLO_VERIFY_REQUEST
    7     In_RSA_CLIENT_HELLO                -> 28 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 8 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 28 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 8 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 20 / Out_TIMEOUT
          In_FINISHED                        -> 28 / Out_TIMEOUT
          In_APPLICATION                     -> 7 / Out_TIMEOUT
          In_CERTIFICATE                     -> 28 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 28 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 28 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
    8     In_RSA_CLIENT_HELLO                -> 8 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 8 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 8 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 8 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 8 / Out_TIMEOUT
          In_APPLICATION                     -> 8 / Out_TIMEOUT
          In_CERTIFICATE                     -> 8 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 8 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 8 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
    9     In_RSA_CLIENT_HELLO                -> 6 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 26 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 6 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 27 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 6 / Out_TIMEOUT
          In_APPLICATION                     -> 9 / Out_TIMEOUT
          In_CERTIFICATE                     -> 6 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 6 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 6 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 6 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 6 / Out_TIMEOUT
    10    In_RSA_CLIENT_HELLO                -> 6 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 7 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 6 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 8 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 6 / Out_TIMEOUT
          In_APPLICATION                     -> 10 / Out_TIMEOUT
          In_CERTIFICATE                     -> 6 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 6 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 6 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 6 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 6 / Out_TIMEOUT
    11    In_RSA_CLIENT_HELLO                -> 16 / Out_SERVER_HELLO_CERTIFICATE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
          In_RSA_CLIENT_KEY_EXCHANGE         -> 11 / Out_HELLO_VERIFY_REQUEST
          In_PSK_CLIENT_HELLO                -> 17 / Out_SERVER_HELLO_SERVER_HELLO_DONE
          In_PSK_CLIENT_KEY_EXCHANGE         -> 11 / Out_HELLO_VERIFY_REQUEST
          In_CHANGE_CIPHER_SPEC              -> 14 / Out_HELLO_VERIFY_REQUEST
          In_FINISHED                        -> 11 / Out_HELLO_VERIFY_REQUEST
          In_APPLICATION                     -> 11 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE                     -> 11 / Out_HELLO_VERIFY_REQUEST
          In_EMPTY_CERTIFICATE               -> 11 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE_VERIFY              -> 11 / Out_HELLO_VERIFY_REQUEST
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_HELLO_VERIFY_REQUEST
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_HELLO_VERIFY_REQUEST
    12    In_RSA_CLIENT_HELLO                -> 5 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 13 / Out_HELLO_VERIFY_REQUEST
          In_PSK_CLIENT_HELLO                -> 5 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 13 / Out_HELLO_VERIFY_REQUEST
          In_CHANGE_CIPHER_SPEC              -> 12 / Out_HELLO_VERIFY_REQUEST
          In_FINISHED                        -> 12 / Out_HELLO_VERIFY_REQUEST
          In_APPLICATION                     -> 12 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE                     -> 12 / Out_HELLO_VERIFY_REQUEST
          In_EMPTY_CERTIFICATE               -> 12 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE_VERIFY              -> 12 / Out_HELLO_VERIFY_REQUEST
          In_Alert_WARNING_CLOSE_NOTIFY      -> 12 / Out_HELLO_VERIFY_REQUEST
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 12 / Out_HELLO_VERIFY_REQUEST
    13    In_RSA_CLIENT_HELLO                -> 5 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 13 / Out_HELLO_VERIFY_REQUEST
          In_PSK_CLIENT_HELLO                -> 5 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 13 / Out_HELLO_VERIFY_REQUEST
          In_CHANGE_CIPHER_SPEC              -> 14 / Out_HELLO_VERIFY_REQUEST
          In_FINISHED                        -> 13 / Out_HELLO_VERIFY_REQUEST
          In_APPLICATION                     -> 13 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE                     -> 13 / Out_HELLO_VERIFY_REQUEST
          In_EMPTY_CERTIFICATE               -> 13 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE_VERIFY              -> 13 / Out_HELLO_VERIFY_REQUEST
          In_Alert_WARNING_CLOSE_NOTIFY      -> 13 / Out_HELLO_VERIFY_REQUEST
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 13 / Out_HELLO_VERIFY_REQUEST
    14    In_RSA_CLIENT_HELLO                -> 14 / Out_HELLO_VERIFY_REQUEST
          In_RSA_CLIENT_KEY_EXCHANGE         -> 14 / Out_HELLO_VERIFY_REQUEST
          In_PSK_CLIENT_HELLO                -> 14 / Out_HELLO_VERIFY_REQUEST
          In_PSK_CLIENT_KEY_EXCHANGE         -> 14 / Out_HELLO_VERIFY_REQUEST
          In_CHANGE_CIPHER_SPEC              -> 14 / Out_HELLO_VERIFY_REQUEST
          In_FINISHED                        -> 14 / Out_HELLO_VERIFY_REQUEST
          In_APPLICATION                     -> 14 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE                     -> 14 / Out_HELLO_VERIFY_REQUEST
          In_EMPTY_CERTIFICATE               -> 14 / Out_HELLO_VERIFY_REQUEST
          In_CERTIFICATE_VERIFY              -> 14 / Out_HELLO_VERIFY_REQUEST
          In_Alert_WARNING_CLOSE_NOTIFY      -> 14 / Out_HELLO_VERIFY_REQUEST
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 14 / Out_HELLO_VERIFY_REQUEST
    15    In_RSA_CLIENT_HELLO                -> 18 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 19 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 18 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 18 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 20 / Out_TIMEOUT
          In_FINISHED                        -> 18 / Out_TIMEOUT
          In_APPLICATION                     -> 15 / Out_TIMEOUT
          In_CERTIFICATE                     -> 18 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 18 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 18 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
    16    In_RSA_CLIENT_HELLO                -> 11 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 7 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 11 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 8 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 11 / Out_TIMEOUT
          In_APPLICATION                     -> 16 / Out_TIMEOUT
          In_CERTIFICATE                     -> 23 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 24 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 11 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
    17    In_RSA_CLIENT_HELLO                -> 11 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 11 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 11 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 15 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 11 / Out_TIMEOUT
          In_APPLICATION                     -> 17 / Out_TIMEOUT
          In_CERTIFICATE                     -> 11 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 11 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 11 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
    18    In_RSA_CLIENT_HELLO                -> 18 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 19 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 18 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 18 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 25 / Out_TIMEOUT
          In_FINISHED                        -> 18 / Out_TIMEOUT
          In_APPLICATION                     -> 18 / Out_TIMEOUT
          In_CERTIFICATE                     -> 18 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 18 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 18 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
    19    In_RSA_CLIENT_HELLO                -> 19 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 19 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 19 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 18 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 19 / Out_TIMEOUT
          In_APPLICATION                     -> 19 / Out_TIMEOUT
          In_CERTIFICATE                     -> 19 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 19 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 19 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
    20    In_RSA_CLIENT_HELLO                -> 14 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 14 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 14 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 14 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 21 / Out_CHANGE_CIPHER_SPEC_FINISHED
          In_APPLICATION                     -> 20 / Out_TIMEOUT
          In_CERTIFICATE                     -> 14 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 14 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 14 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 14 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 14 / Out_TIMEOUT
    21    In_RSA_CLIENT_HELLO                -> 22 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 21 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 22 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 21 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 21 / Out_TIMEOUT
          In_APPLICATION                     -> 21 / Out_APPLICATION
          In_CERTIFICATE                     -> 21 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 21 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 21 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 14 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 14 / Out_TIMEOUT
    22    In_RSA_CLIENT_HELLO                -> 22 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 22 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 22 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 22 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 22 / Out_TIMEOUT
          In_APPLICATION                     -> 14 / Out_TIMEOUT
          In_CERTIFICATE                     -> 22 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 22 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 22 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 14 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 14 / Out_TIMEOUT
    23    In_RSA_CLIENT_HELLO                -> 11 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 26 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 11 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 27 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 11 / Out_TIMEOUT
          In_APPLICATION                     -> 23 / Out_TIMEOUT
          In_CERTIFICATE                     -> 11 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 11 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 11 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
    24    In_RSA_CLIENT_HELLO                -> 11 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 7 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 11 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 8 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 11 / Out_TIMEOUT
          In_APPLICATION                     -> 24 / Out_TIMEOUT
          In_CERTIFICATE                     -> 11 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 11 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 11 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
    25    In_RSA_CLIENT_HELLO                -> 25 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 25 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 25 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 25 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 25 / Out_TIMEOUT
          In_APPLICATION                     -> 25 / Out_TIMEOUT
          In_CERTIFICATE                     -> 25 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 25 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 25 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 14 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 14 / Out_TIMEOUT
    26    In_RSA_CLIENT_HELLO                -> 11 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 11 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 11 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 11 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 11 / Out_TIMEOUT
          In_APPLICATION                     -> 26 / Out_TIMEOUT
          In_CERTIFICATE                     -> 11 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 11 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 7 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
    27    In_RSA_CLIENT_HELLO                -> 11 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 11 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 11 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 11 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 5 / Out_TIMEOUT
          In_FINISHED                        -> 11 / Out_TIMEOUT
          In_APPLICATION                     -> 27 / Out_TIMEOUT
          In_CERTIFICATE                     -> 11 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 11 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 8 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
    28    In_RSA_CLIENT_HELLO                -> 28 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 8 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 28 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 8 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 25 / Out_TIMEOUT
          In_FINISHED                        -> 28 / Out_TIMEOUT
          In_APPLICATION                     -> 28 / Out_TIMEOUT
          In_CERTIFICATE                     -> 28 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 28 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 28 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
-}
gnutlsV3V5V19PskRsaCertNreq :: MealyAutomaton Int GnutlsV3V5V19PskRsaCertNreqInput GnutlsV3V5V19PskRsaCertNreqOutput
gnutlsV3V5V19PskRsaCertNreq =
    case mkMealyAutomatonTable 29 0 deltaTable lambdaTable of
        Right m -> m
        Left err -> error ("haal-gen: invalid transition table: " ++ err)
  where
    deltaTable =
        "\1\1\1\1\2\1\1\1\1\1\1\1\
        \\3\1\4\1\2\1\1\1\1\1\1\1\
        \\5\2\5\2\2\2\2\2\2\2\2\2\
        \\6\7\6\8\5\6\3\9\10\6\6\6\
        \\6\11\6\15\5\6\4\6\6\6\6\6\
        \\5\5\5\5\5\5\5\5\5\5\5\5\
        \\3\11\4\11\12\6\6\6\6\6\6\6\
        \\28\8\28\8\20\28\7\28\28\28\11\11\
        \\8\8\8\8\5\8\8\8\8\8\11\11\
        \\6\26\6\27\5\6\9\6\6\6\6\6\
        \\6\7\6\8\5\6\10\6\6\6\6\6\
        \\16\11\17\11\14\11\11\11\11\11\11\11\
        \\5\13\5\13\12\12\12\12\12\12\12\12\
        \\5\13\5\13\14\13\13\13\13\13\13\13\
        \\14\14\14\14\14\14\14\14\14\14\14\14\
        \\18\19\18\18\20\18\15\18\18\18\11\11\
        \\11\7\11\8\5\11\16\23\24\11\11\11\
        \\11\11\11\15\5\11\17\11\11\11\11\11\
        \\18\19\18\18\25\18\18\18\18\18\11\11\
        \\19\19\19\18\5\19\19\19\19\19\11\11\
        \\14\14\14\14\5\21\20\14\14\14\14\14\
        \\22\21\22\21\5\21\21\21\21\21\14\14\
        \\22\22\22\22\5\22\14\22\22\22\14\14\
        \\11\26\11\27\5\11\23\11\11\11\11\11\
        \\11\7\11\8\5\11\24\11\11\11\11\11\
        \\25\25\25\25\5\25\25\25\25\25\14\14\
        \\11\11\11\11\5\11\26\11\11\7\11\11\
        \\11\11\11\11\5\11\27\11\11\8\11\11\
        \\28\8\28\8\25\28\28\28\28\28\11\11"
    lambdaTable =
        "\0\0\0\0\0\0\0\0\0\0\0\0\
        \\1\0\2\0\0\0\0\0\0\0\0\0\
        \\3\0\3\0\0\0\0\0\0\0\0\0\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\1\0\2\0\0\0\0\0\0\0\0\0\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\1\0\2\0\0\0\0\0\0\0\0\0\
        \\3\0\3\0\0\0\0\0\0\0\0\0\
        \\3\0\3\0\0\0\0\0\0\0\0\0\
        \\0\0\0\0\0\0\0\0\0\0\0\0\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\4\3\3\3\3\3\3\
        \\3\3\3\3\3\3\5\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3\
        \\3\3\3\3\3\3\3\3\3\3\3\3"
