-- Generated by haal-gen. Do not edit manually.
module Haal.Models.DTLS.MbedtlsAllCertReq
    ( MbedtlsAllCertReqInput (..)
    , MbedtlsAllCertReqOutput (..)
    , mbedtlsAllCertReq
    ) where

import Haal.Automaton.MealyAutomaton (MealyAutomaton, mkMealyAutomatonTable)

data MbedtlsAllCertReqInput
    = In_ECDH_CLIENT_HELLO
    | In_ECDH_CLIENT_KEY_EXCHANGE
    | In_DH_CLIENT_HELLO
    | In_DH_CLIENT_KEY_EXCHANGE
    | In_PSK_CLIENT_HELLO
    | In_PSK_CLIENT_KEY_EXCHANGE
    | In_RSA_CLIENT_HELLO
    | In_RSA_CLIENT_KEY_EXCHANGE
    | In_CHANGE_CIPHER_SPEC
    | In_FINISHED
    | In_APPLICATION
    | In_CERTIFICATE
    | In_EMPTY_CERTIFICATE
    | In_CERTIFICATE_VERIFY
    | In_Alert_WARNING_CLOSE_NOTIFY
    | In_Alert_FATAL_UNEXPECTED_MESSAGE
    deriving (Show, Eq, Ord, Enum, Bounded)

data MbedtlsAllCertReqOutput
    = Out_HELLO_VERIFY_REQUEST
    | Out_TIMEOUT
    | Out_SERVER_HELLO_CERTIFICATE_ECDHE_SERVER_KEY_EXCHANGE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
    | Out_SERVER_HELLO_CERTIFICATE_DHE_SERVER_KEY_EXCHANGE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
    | Out_SERVER_HELLO_SERVER_HELLO_DONE
    | Out_SERVER_HELLO_CERTIFICATE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
    | Out_Alert_FATAL_DECODE_ERROR
    | Out_Alert_FATAL_UNKNOWN_PSK_IDENTITY
    | Out_Alert_FATAL_UNEXPECTED_MESSAGE
    | Out_CHANGE_CIPHER_SPEC_FINISHED
    | Out_Alert_WARNING_NO_RENEGOTIATION
    | Out_APPLICATION
    | Out_Alert_WARNING_CLOSE_NOTIFY
    | Out_Alert_FATAL_BAD_RECORD_MAC
    deriving (Show, Eq, Ord, Enum, Bounded)

{- Transitions (state  input -> next state / output):
    0     In_ECDH_CLIENT_HELLO               -> 1 / Out_HELLO_VERIFY_REQUEST
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 0 / Out_TIMEOUT
          In_DH_CLIENT_HELLO                 -> 1 / Out_HELLO_VERIFY_REQUEST
          In_DH_CLIENT_KEY_EXCHANGE          -> 0 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 1 / Out_HELLO_VERIFY_REQUEST
          In_PSK_CLIENT_KEY_EXCHANGE         -> 0 / Out_TIMEOUT
          In_RSA_CLIENT_HELLO                -> 1 / Out_HELLO_VERIFY_REQUEST
          In_RSA_CLIENT_KEY_EXCHANGE         -> 0 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 0 / Out_TIMEOUT
          In_APPLICATION                     -> 0 / Out_TIMEOUT
          In_CERTIFICATE                     -> 0 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 0 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 0 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 0 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 0 / Out_TIMEOUT
    1     In_ECDH_CLIENT_HELLO               -> 3 / Out_SERVER_HELLO_CERTIFICATE_ECDHE_SERVER_KEY_EXCHANGE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 1 / Out_TIMEOUT
          In_DH_CLIENT_HELLO                 -> 4 / Out_SERVER_HELLO_CERTIFICATE_DHE_SERVER_KEY_EXCHANGE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
          In_DH_CLIENT_KEY_EXCHANGE          -> 1 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 5 / Out_SERVER_HELLO_SERVER_HELLO_DONE
          In_PSK_CLIENT_KEY_EXCHANGE         -> 1 / Out_TIMEOUT
          In_RSA_CLIENT_HELLO                -> 6 / Out_SERVER_HELLO_CERTIFICATE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
          In_RSA_CLIENT_KEY_EXCHANGE         -> 1 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_TIMEOUT
          In_APPLICATION                     -> 1 / Out_TIMEOUT
          In_CERTIFICATE                     -> 1 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 1 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 1 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    2     In_ECDH_CLIENT_HELLO               -> 2 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 2 / Out_TIMEOUT
          In_DH_CLIENT_HELLO                 -> 2 / Out_TIMEOUT
          In_DH_CLIENT_KEY_EXCHANGE          -> 2 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 2 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 2 / Out_TIMEOUT
          In_RSA_CLIENT_HELLO                -> 2 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 2 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 2 / Out_TIMEOUT
          In_APPLICATION                     -> 2 / Out_TIMEOUT
          In_CERTIFICATE                     -> 2 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 2 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 2 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
    3     In_ECDH_CLIENT_HELLO               -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_DH_CLIENT_HELLO                 -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_DH_CLIENT_KEY_EXCHANGE          -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_PSK_CLIENT_HELLO                -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_PSK_CLIENT_KEY_EXCHANGE         -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_RSA_CLIENT_HELLO                -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_RSA_CLIENT_KEY_EXCHANGE         -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 12 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 1 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    4     In_ECDH_CLIENT_HELLO               -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_DH_CLIENT_HELLO                 -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_DH_CLIENT_KEY_EXCHANGE          -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_PSK_CLIENT_HELLO                -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_PSK_CLIENT_KEY_EXCHANGE         -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_RSA_CLIENT_HELLO                -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_RSA_CLIENT_KEY_EXCHANGE         -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_APPLICATION                     -> 4 / Out_TIMEOUT
          In_CERTIFICATE                     -> 14 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 1 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    5     In_ECDH_CLIENT_HELLO               -> 1 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 1 / Out_TIMEOUT
          In_DH_CLIENT_HELLO                 -> 1 / Out_TIMEOUT
          In_DH_CLIENT_KEY_EXCHANGE          -> 1 / Out_Alert_FATAL_UNKNOWN_PSK_IDENTITY
          In_PSK_CLIENT_HELLO                -> 1 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 8 / Out_TIMEOUT
          In_RSA_CLIENT_HELLO                -> 1 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 1 / Out_Alert_FATAL_UNKNOWN_PSK_IDENTITY
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_TIMEOUT
          In_APPLICATION                     -> 5 / Out_TIMEOUT
          In_CERTIFICATE                     -> 1 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 1 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 1 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    6     In_ECDH_CLIENT_HELLO               -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_DH_CLIENT_HELLO                 -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_DH_CLIENT_KEY_EXCHANGE          -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_PSK_CLIENT_HELLO                -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_PSK_CLIENT_KEY_EXCHANGE         -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_RSA_CLIENT_HELLO                -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_RSA_CLIENT_KEY_EXCHANGE         -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_APPLICATION                     -> 6 / Out_TIMEOUT
          In_CERTIFICATE                     -> 7 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 1 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 1 / Out_Alert_FATAL_DECODE_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    7     In_ECDH_CLIENT_HELLO               -> 1 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 10 / Out_TIMEOUT
          In_DH_CLIENT_HELLO                 -> 1 / Out_TIMEOUT
          In_DH_CLIENT_KEY_EXCHANGE          -> 10 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 1 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 10 / Out_TIMEOUT
          In_RSA_CLIENT_HELLO                -> 1 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 11 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_TIMEOUT
          In_APPLICATION                     -> 7 / Out_TIMEOUT
          In_CERTIFICATE                     -> 1 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 1 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 1 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    8     In_ECDH_CLIENT_HELLO               -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_DH_CLIENT_HELLO                 -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_DH_CLIENT_KEY_EXCHANGE          -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_PSK_CLIENT_HELLO                -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_PSK_CLIENT_KEY_EXCHANGE         -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_RSA_CLIENT_HELLO                -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_RSA_CLIENT_KEY_EXCHANGE         -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_CHANGE_CIPHER_SPEC              -> 9 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_APPLICATION                     -> 8 / Out_TIMEOUT
          In_CERTIFICATE                     -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_EMPTY_CERTIFICATE               -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_CERTIFICATE_VERIFY              -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    9     In_ECDH_CLIENT_HELLO               -> 2 / Out_Alert_FATAL_DECODE_ERROR
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 2 / Out_Alert_FATAL_DECODE_ERROR
          In_DH_CLIENT_HELLO                 -> 2 / Out_Alert_FATAL_DECODE_ERROR
          In_DH_CLIENT_KEY_EXCHANGE          -> 2 / Out_Alert_FATAL_DECODE_ERROR
          In_PSK_CLIENT_HELLO                -> 2 / Out_Alert_FATAL_DECODE_ERROR
          In_PSK_CLIENT_KEY_EXCHANGE         -> 2 / Out_Alert_FATAL_DECODE_ERROR
          In_RSA_CLIENT_HELLO                -> 2 / Out_Alert_FATAL_DECODE_ERROR
          In_RSA_CLIENT_KEY_EXCHANGE         -> 2 / Out_Alert_FATAL_DECODE_ERROR
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 13 / Out_CHANGE_CIPHER_SPEC_FINISHED
          In_APPLICATION                     -> 9 / Out_TIMEOUT
          In_CERTIFICATE                     -> 2 / Out_Alert_FATAL_DECODE_ERROR
          In_EMPTY_CERTIFICATE               -> 2 / Out_Alert_FATAL_DECODE_ERROR
          In_CERTIFICATE_VERIFY              -> 2 / Out_Alert_FATAL_DECODE_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
    10    In_ECDH_CLIENT_HELLO               -> 1 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 1 / Out_TIMEOUT
          In_DH_CLIENT_HELLO                 -> 1 / Out_TIMEOUT
          In_DH_CLIENT_KEY_EXCHANGE          -> 1 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 1 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 1 / Out_TIMEOUT
          In_RSA_CLIENT_HELLO                -> 1 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 1 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_TIMEOUT
          In_APPLICATION                     -> 10 / Out_TIMEOUT
          In_CERTIFICATE                     -> 1 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 1 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 15 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    11    In_ECDH_CLIENT_HELLO               -> 1 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 1 / Out_TIMEOUT
          In_DH_CLIENT_HELLO                 -> 1 / Out_TIMEOUT
          In_DH_CLIENT_KEY_EXCHANGE          -> 1 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 1 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 1 / Out_TIMEOUT
          In_RSA_CLIENT_HELLO                -> 1 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 1 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_TIMEOUT
          In_APPLICATION                     -> 11 / Out_TIMEOUT
          In_CERTIFICATE                     -> 1 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 1 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 8 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    12    In_ECDH_CLIENT_HELLO               -> 1 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 11 / Out_TIMEOUT
          In_DH_CLIENT_HELLO                 -> 1 / Out_TIMEOUT
          In_DH_CLIENT_KEY_EXCHANGE          -> 1 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 1 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 1 / Out_TIMEOUT
          In_RSA_CLIENT_HELLO                -> 1 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 1 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_TIMEOUT
          In_APPLICATION                     -> 12 / Out_TIMEOUT
          In_CERTIFICATE                     -> 1 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 1 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 1 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    13    In_ECDH_CLIENT_HELLO               -> 13 / Out_Alert_WARNING_NO_RENEGOTIATION
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 13 / Out_TIMEOUT
          In_DH_CLIENT_HELLO                 -> 13 / Out_Alert_WARNING_NO_RENEGOTIATION
          In_DH_CLIENT_KEY_EXCHANGE          -> 13 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 13 / Out_Alert_WARNING_NO_RENEGOTIATION
          In_PSK_CLIENT_KEY_EXCHANGE         -> 13 / Out_TIMEOUT
          In_RSA_CLIENT_HELLO                -> 13 / Out_Alert_WARNING_NO_RENEGOTIATION
          In_RSA_CLIENT_KEY_EXCHANGE         -> 13 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 13 / Out_TIMEOUT
          In_APPLICATION                     -> 13 / Out_APPLICATION
          In_CERTIFICATE                     -> 13 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 13 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 13 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
    14    In_ECDH_CLIENT_HELLO               -> 1 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 1 / Out_TIMEOUT
          In_DH_CLIENT_HELLO                 -> 1 / Out_TIMEOUT
          In_DH_CLIENT_KEY_EXCHANGE          -> 11 / Out_TIMEOUT
          In_PSK_CLIENT_HELLO                -> 1 / Out_TIMEOUT
          In_PSK_CLIENT_KEY_EXCHANGE         -> 10 / Out_TIMEOUT
          In_RSA_CLIENT_HELLO                -> 1 / Out_TIMEOUT
          In_RSA_CLIENT_KEY_EXCHANGE         -> 10 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_TIMEOUT
          In_APPLICATION                     -> 14 / Out_TIMEOUT
          In_CERTIFICATE                     -> 1 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 1 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 1 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    15    In_ECDH_CLIENT_HELLO               -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_DH_CLIENT_HELLO                 -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_DH_CLIENT_KEY_EXCHANGE          -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_PSK_CLIENT_HELLO                -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_PSK_CLIENT_KEY_EXCHANGE         -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_RSA_CLIENT_HELLO                -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_RSA_CLIENT_KEY_EXCHANGE         -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_CHANGE_CIPHER_SPEC              -> 16 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_APPLICATION                     -> 15 / Out_TIMEOUT
          In_CERTIFICATE                     -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_EMPTY_CERTIFICATE               -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_CERTIFICATE_VERIFY              -> 1 / Out_Alert_FATAL_UNEXPECTED_MESSAGE
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    16    In_ECDH_CLIENT_HELLO               -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
          In_DH_CLIENT_HELLO                 -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
          In_DH_CLIENT_KEY_EXCHANGE          -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
          In_PSK_CLIENT_HELLO                -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
          In_PSK_CLIENT_KEY_EXCHANGE         -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
          In_RSA_CLIENT_HELLO                -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
          In_RSA_CLIENT_KEY_EXCHANGE         -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
          In_FINISHED                        -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
          In_APPLICATION                     -> 16 / Out_TIMEOUT
          In_CERTIFICATE                     -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
          In_EMPTY_CERTIFICATE               -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
          In_CERTIFICATE_VERIFY              -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_Alert_FATAL_BAD_RECORD_MAC
-}
mbedtlsAllCertReq :: MealyAutomaton Int MbedtlsAllCertReqInput MbedtlsAllCertReqOutput
mbedtlsAllCertReq =
    case mkMealyAutomatonTable 17 0 deltaTable lambdaTable of
        Right m -> m
        Left err -> error ("haal-gen: invalid transition table: " ++ err)
  where
    deltaTable =
        "\1\0\1\0\1\0\1\0\2\0\0\0\0\0\0\0\
        \\3\1\4\1\5\1\6\1\2\1\1\1\1\1\1\1\
        \\2\2\2\2\2\2\2\2\2\2\2\2\2\2\2\2\
        \\1\1\1\1\1\1\1\1\2\1\3\12\1\1\1\1\
        \\1\1\1\1\1\1\1\1\2\1\4\14\1\1\1\1\
        \\1\1\1\1\1\8\1\1\2\1\5\1\1\1\1\1\
        \\1\1\1\1\1\1\1\1\2\1\6\7\1\1\1\1\
        \\1\10\1\10\1\10\1\11\2\1\7\1\1\1\1\1\
        \\1\1\1\1\1\1\1\1\9\1\8\1\1\1\1\1\
        \\2\2\2\2\2\2\2\2\2\13\9\2\2\2\2\2\
        \\1\1\1\1\1\1\1\1\2\1\10\1\1\15\1\1\
        \\1\1\1\1\1\1\1\1\2\1\11\1\1\8\1\1\
        \\1\11\1\1\1\1\1\1\2\1\12\1\1\1\1\1\
        \\13\13\13\13\13\13\13\13\2\13\13\13\13\13\2\2\
        \\1\1\1\11\1\10\1\10\2\1\14\1\1\1\1\1\
        \\1\1\1\1\1\1\1\1\16\1\15\1\1\1\1\1\
        \\2\2\2\2\2\2\2\2\2\2\16\2\2\2\2\2"
    lambdaTable =
        "\0\1\0\1\0\1\0\1\1\1\1\1\1\1\1\1\
        \\2\1\3\1\4\1\5\1\1\1\1\1\1\1\1\1\
        \\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\
        \\6\6\6\6\6\6\6\6\1\6\1\1\1\6\1\1\
        \\6\6\6\6\6\6\6\6\1\6\1\1\1\6\1\1\
        \\1\1\1\7\1\1\1\7\1\1\1\1\1\1\1\1\
        \\6\6\6\6\6\6\6\6\1\6\1\1\1\6\1\1\
        \\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\
        \\8\8\8\8\8\8\8\8\1\8\1\8\8\8\1\1\
        \\6\6\6\6\6\6\6\6\1\9\1\6\6\6\1\1\
        \\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\
        \\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\
        \\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\
        \\10\1\10\1\10\1\10\1\1\1\11\1\1\1\12\1\
        \\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\
        \\8\8\8\8\8\8\8\8\1\8\1\8\8\8\1\1\
        \\13\13\13\13\13\13\13\13\13\13\1\13\13\13\13\13"
