-- Generated by haal-gen. Do not edit manually.
module Haal.Models.DTLS.PionEcdheCertReq
    ( PionEcdheCertReqInput (..)
    , PionEcdheCertReqOutput (..)
    , pionEcdheCertReq
    ) where

import Haal.Automaton.MealyAutomaton (MealyAutomaton, mkMealyAutomatonTable)

data PionEcdheCertReqInput
    = In_ECDH_CLIENT_HELLO
    | In_ECDH_CLIENT_KEY_EXCHANGE
    | In_CHANGE_CIPHER_SPEC
    | In_FINISHED
    | In_APPLICATION
    | In_CERTIFICATE
    | In_EMPTY_CERTIFICATE
    | In_CERTIFICATE_VERIFY
    | In_Alert_WARNING_CLOSE_NOTIFY
    | In_Alert_FATAL_UNEXPECTED_MESSAGE
    deriving (Show, Eq, Ord, Enum, Bounded)

data PionEcdheCertReqOutput
    = Out_HELLO_VERIFY_REQUEST
    | Out_TIMEOUT
    | Out_Alert_FATAL_CLOSE_NOTIFY
    | Out_SOCKET_CLOSED
    | Out_SERVER_HELLO_CERTIFICATE_ECDHE_SERVER_KEY_EXCHANGE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
    | Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
    | Out_Alert_FATAL_HANDSHAKE_FAILURE
    | Out_Alert_FATAL_BAD_CERTIFICATE
    | Out_CHANGE_CIPHER_SPEC_FINISHED
    | Out_Alert_FATAL_DECODE_ERROR
    | Out_APPLICATION
    deriving (Show, Eq, Ord, Enum, Bounded)

{- Transitions (state  input -> next state / output):
    0     In_ECDH_CLIENT_HELLO               -> 1 / Out_HELLO_VERIFY_REQUEST
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 2 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 2 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 2 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 2 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 2 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    1     In_ECDH_CLIENT_HELLO               -> 5 / Out_SERVER_HELLO_CERTIFICATE_ECDHE_SERVER_KEY_EXCHANGE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 2 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 2 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 2 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 2 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 2 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    2     In_ECDH_CLIENT_HELLO               -> 2 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 2 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 2 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 2 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 2 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 2 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    3     In_ECDH_CLIENT_HELLO               -> 3 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 3 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 3 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 3 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 3 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 3 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 3 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 3 / Out_TIMEOUT
    4     In_ECDH_CLIENT_HELLO               -> 4 / Out_SOCKET_CLOSED
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 4 / Out_SOCKET_CLOSED
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_SOCKET_CLOSED
          In_FINISHED                        -> 4 / Out_SOCKET_CLOSED
          In_APPLICATION                     -> 4 / Out_SOCKET_CLOSED
          In_CERTIFICATE                     -> 4 / Out_SOCKET_CLOSED
          In_EMPTY_CERTIFICATE               -> 4 / Out_SOCKET_CLOSED
          In_CERTIFICATE_VERIFY              -> 4 / Out_SOCKET_CLOSED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_SOCKET_CLOSED
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_SOCKET_CLOSED
    5     In_ECDH_CLIENT_HELLO               -> 6 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 7 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 8 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 9 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 10 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 11 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    6     In_ECDH_CLIENT_HELLO               -> 6 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 13 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 8 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 22 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 23 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 11 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    7     In_ECDH_CLIENT_HELLO               -> 12 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 13 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 14 / Out_TIMEOUT
          In_FINISHED                        -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 15 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 16 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    8     In_ECDH_CLIENT_HELLO               -> 8 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 8 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 18 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 18 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 11 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    9     In_ECDH_CLIENT_HELLO               -> 19 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 20 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 21 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 22 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 23 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 24 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    10    In_ECDH_CLIENT_HELLO               -> 19 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 64 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 21 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 22 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 23 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 24 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    11    In_ECDH_CLIENT_HELLO               -> 11 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 49 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 11 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 50 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 51 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 11 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    12    In_ECDH_CLIENT_HELLO               -> 12 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 13 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 37 / Out_TIMEOUT
          In_FINISHED                        -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 15 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 16 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 53 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    13    In_ECDH_CLIENT_HELLO               -> 12 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 13 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 17 / Out_TIMEOUT
          In_FINISHED                        -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 15 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 16 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    14    In_ECDH_CLIENT_HELLO               -> 37 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 17 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 27 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 38 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    15    In_ECDH_CLIENT_HELLO               -> 25 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 26 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 27 / Out_TIMEOUT
          In_FINISHED                        -> 28 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 15 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 16 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 29 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    16    In_ECDH_CLIENT_HELLO               -> 25 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 55 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 38 / Out_TIMEOUT
          In_FINISHED                        -> 28 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 15 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 16 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 29 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    17    In_ECDH_CLIENT_HELLO               -> 37 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 17 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 27 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 38 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    18    In_ECDH_CLIENT_HELLO               -> 21 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 21 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 18 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 18 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 24 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    19    In_ECDH_CLIENT_HELLO               -> 19 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 19 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 21 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 22 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 23 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 24 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    20    In_ECDH_CLIENT_HELLO               -> 30 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 25 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 31 / Out_TIMEOUT
          In_FINISHED                        -> 4 / Out_Alert_FATAL_BAD_CERTIFICATE
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 15 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 16 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 32 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    21    In_ECDH_CLIENT_HELLO               -> 21 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 21 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 21 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 18 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 18 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 24 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    22    In_ECDH_CLIENT_HELLO               -> 19 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 26 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 21 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 22 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 23 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 24 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    23    In_ECDH_CLIENT_HELLO               -> 19 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 55 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 21 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 22 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 23 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 24 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    24    In_ECDH_CLIENT_HELLO               -> 24 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 24 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 24 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 50 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 51 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 24 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    25    In_ECDH_CLIENT_HELLO               -> 25 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 25 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 40 / Out_TIMEOUT
          In_FINISHED                        -> 28 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 15 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 16 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 29 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    26    In_ECDH_CLIENT_HELLO               -> 30 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 25 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 44 / Out_TIMEOUT
          In_FINISHED                        -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 15 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 16 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_BAD_CERTIFICATE
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    27    In_ECDH_CLIENT_HELLO               -> 40 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 44 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 45 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 27 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 38 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 46 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    28    In_ECDH_CLIENT_HELLO               -> 28 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 28 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 45 / Out_TIMEOUT
          In_FINISHED                        -> 28 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 54 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 54 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 29 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    29    In_ECDH_CLIENT_HELLO               -> 29 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 29 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 46 / Out_TIMEOUT
          In_FINISHED                        -> 29 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 35 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 36 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 29 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    30    In_ECDH_CLIENT_HELLO               -> 30 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 25 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 47 / Out_TIMEOUT
          In_FINISHED                        -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 15 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 16 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 29 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    31    In_ECDH_CLIENT_HELLO               -> 47 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 40 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 4 / Out_Alert_FATAL_BAD_CERTIFICATE
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 27 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 38 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 33 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    32    In_ECDH_CLIENT_HELLO               -> 4 / Out_Alert_FATAL_BAD_CERTIFICATE
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 29 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 33 / Out_TIMEOUT
          In_FINISHED                        -> 34 / Out_CHANGE_CIPHER_SPEC_FINISHED
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 35 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 36 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 29 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    33    In_ECDH_CLIENT_HELLO               -> 4 / Out_Alert_FATAL_BAD_CERTIFICATE
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 46 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 48 / Out_CHANGE_CIPHER_SPEC_FINISHED
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 42 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 43 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 46 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    34    In_ECDH_CLIENT_HELLO               -> 34 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 34 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 48 / Out_TIMEOUT
          In_FINISHED                        -> 34 / Out_TIMEOUT
          In_APPLICATION                     -> 4 / Out_APPLICATION
          In_CERTIFICATE                     -> 34 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 34 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 34 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    35    In_ECDH_CLIENT_HELLO               -> 29 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 59 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 42 / Out_TIMEOUT
          In_FINISHED                        -> 29 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 35 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 36 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 29 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    36    In_ECDH_CLIENT_HELLO               -> 29 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 60 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 43 / Out_TIMEOUT
          In_FINISHED                        -> 29 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 35 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 36 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 29 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    37    In_ECDH_CLIENT_HELLO               -> 37 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 17 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 27 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 38 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 39 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    38    In_ECDH_CLIENT_HELLO               -> 40 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 56 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 45 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 27 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 38 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 46 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    39    In_ECDH_CLIENT_HELLO               -> 39 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 41 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 39 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 42 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 43 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 39 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    40    In_ECDH_CLIENT_HELLO               -> 40 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 40 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 45 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 27 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 38 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 46 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    41    In_ECDH_CLIENT_HELLO               -> 39 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 41 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 39 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 42 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 43 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    42    In_ECDH_CLIENT_HELLO               -> 46 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 58 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 46 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 42 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 43 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 46 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    43    In_ECDH_CLIENT_HELLO               -> 46 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 61 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 46 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 42 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 43 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 46 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    44    In_ECDH_CLIENT_HELLO               -> 47 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 40 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 27 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 38 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_BAD_CERTIFICATE
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    45    In_ECDH_CLIENT_HELLO               -> 45 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 45 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 45 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 57 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 57 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 46 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    46    In_ECDH_CLIENT_HELLO               -> 46 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 46 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 46 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 42 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 43 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 46 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    47    In_ECDH_CLIENT_HELLO               -> 47 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 40 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 27 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 38 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 46 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    48    In_ECDH_CLIENT_HELLO               -> 48 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 48 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 48 / Out_TIMEOUT
          In_APPLICATION                     -> 4 / Out_APPLICATION
          In_CERTIFICATE                     -> 48 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 48 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 48 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    49    In_ECDH_CLIENT_HELLO               -> 11 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 49 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 11 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 50 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 51 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    50    In_ECDH_CLIENT_HELLO               -> 24 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 52 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 24 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 50 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 51 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 24 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    51    In_ECDH_CLIENT_HELLO               -> 24 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 62 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 24 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 50 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 51 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 24 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    52    In_ECDH_CLIENT_HELLO               -> 24 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 24 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 24 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 50 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 51 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_BAD_CERTIFICATE
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    53    In_ECDH_CLIENT_HELLO               -> 53 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 63 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 39 / Out_TIMEOUT
          In_FINISHED                        -> 53 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 35 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 36 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 53 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    54    In_ECDH_CLIENT_HELLO               -> 28 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_CHANGE_CIPHER_SPEC              -> 57 / Out_TIMEOUT
          In_FINISHED                        -> 28 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 54 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 54 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 29 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    55    In_ECDH_CLIENT_HELLO               -> 30 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 25 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 56 / Out_TIMEOUT
          In_FINISHED                        -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 15 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 16 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    56    In_ECDH_CLIENT_HELLO               -> 47 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 40 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 27 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 38 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    57    In_ECDH_CLIENT_HELLO               -> 45 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 45 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 57 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 57 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 46 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    58    In_ECDH_CLIENT_HELLO               -> 46 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 46 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 46 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 42 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 43 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_BAD_CERTIFICATE
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    59    In_ECDH_CLIENT_HELLO               -> 29 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 29 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 58 / Out_TIMEOUT
          In_FINISHED                        -> 29 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 35 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 36 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_BAD_CERTIFICATE
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    60    In_ECDH_CLIENT_HELLO               -> 29 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 29 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 61 / Out_TIMEOUT
          In_FINISHED                        -> 29 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 35 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 36 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    61    In_ECDH_CLIENT_HELLO               -> 46 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 46 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 46 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 42 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 43 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    62    In_ECDH_CLIENT_HELLO               -> 24 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 24 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 3 / Out_TIMEOUT
          In_FINISHED                        -> 24 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 50 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 51 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    63    In_ECDH_CLIENT_HELLO               -> 53 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 63 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 41 / Out_TIMEOUT
          In_FINISHED                        -> 53 / Out_TIMEOUT
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 35 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 36 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    64    In_ECDH_CLIENT_HELLO               -> 30 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 25 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 65 / Out_TIMEOUT
          In_FINISHED                        -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 15 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 16 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    65    In_ECDH_CLIENT_HELLO               -> 47 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 40 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 4 / Out_Alert_FATAL_DECODE_ERROR
          In_FINISHED                        -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 27 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 38 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_NO_CERTIFICATE_RESERVED
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_FATAL_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
-}
pionEcdheCertReq :: MealyAutomaton Int PionEcdheCertReqInput PionEcdheCertReqOutput
pionEcdheCertReq =
    case mkMealyAutomatonTable 66 0 deltaTable lambdaTable of
        Right m -> m
        Left err -> error ("haal-gen: invalid transition table: " ++ err)
  where
    deltaTable =
        "\1\2\3\2\3\2\2\2\4\4\
        \\5\2\3\2\3\2\2\2\4\4\
        \\2\2\3\2\3\2\2\2\4\4\
        \\3\3\3\3\3\3\3\3\3\3\
        \\4\4\4\4\4\4\4\4\4\4\
        \\6\7\3\8\3\9\10\11\4\4\
        \\6\13\3\8\3\22\23\11\4\4\
        \\12\13\14\4\3\15\16\4\4\4\
        \\8\4\3\8\3\18\18\11\4\4\
        \\19\20\3\21\3\22\23\24\4\4\
        \\19\64\3\21\3\22\23\24\4\4\
        \\11\49\3\11\3\50\51\11\4\4\
        \\12\13\37\4\3\15\16\53\4\4\
        \\12\13\17\4\3\15\16\4\4\4\
        \\37\17\4\4\3\27\38\4\4\4\
        \\25\26\27\28\3\15\16\29\4\4\
        \\25\55\38\28\3\15\16\29\4\4\
        \\37\17\4\4\3\27\38\4\4\4\
        \\21\4\3\21\3\18\18\24\4\4\
        \\19\19\3\21\3\22\23\24\4\4\
        \\30\25\31\4\3\15\16\32\4\4\
        \\21\21\3\21\3\18\18\24\4\4\
        \\19\26\3\21\3\22\23\24\4\4\
        \\19\55\3\21\3\22\23\24\4\4\
        \\24\24\3\24\3\50\51\24\4\4\
        \\25\25\40\28\3\15\16\29\4\4\
        \\30\25\44\4\3\15\16\4\4\4\
        \\40\44\4\45\3\27\38\46\4\4\
        \\28\28\45\28\3\54\54\29\4\4\
        \\29\29\46\29\3\35\36\29\4\4\
        \\30\25\47\4\3\15\16\29\4\4\
        \\47\40\4\4\3\27\38\33\4\4\
        \\4\29\33\34\3\35\36\29\4\4\
        \\4\46\4\48\3\42\43\46\4\4\
        \\34\34\48\34\4\34\34\34\4\4\
        \\29\59\42\29\3\35\36\29\4\4\
        \\29\60\43\29\3\35\36\29\4\4\
        \\37\17\4\4\3\27\38\39\4\4\
        \\40\56\4\45\3\27\38\46\4\4\
        \\39\41\4\39\3\42\43\39\4\4\
        \\40\40\4\45\3\27\38\46\4\4\
        \\39\41\4\39\3\42\43\4\4\4\
        \\46\58\4\46\3\42\43\46\4\4\
        \\46\61\4\46\3\42\43\46\4\4\
        \\47\40\4\4\3\27\38\4\4\4\
        \\45\45\4\45\3\57\57\46\4\4\
        \\46\46\4\46\3\42\43\46\4\4\
        \\47\40\4\4\3\27\38\46\4\4\
        \\48\48\4\48\4\48\48\48\4\4\
        \\11\49\3\11\3\50\51\4\4\4\
        \\24\52\3\24\3\50\51\24\4\4\
        \\24\62\3\24\3\50\51\24\4\4\
        \\24\24\3\24\3\50\51\4\4\4\
        \\53\63\39\53\3\35\36\53\4\4\
        \\28\4\57\28\3\54\54\29\4\4\
        \\30\25\56\4\3\15\16\4\4\4\
        \\47\40\4\4\3\27\38\4\4\4\
        \\45\4\4\45\3\57\57\46\4\4\
        \\46\46\4\46\3\42\43\4\4\4\
        \\29\29\58\29\3\35\36\4\4\4\
        \\29\29\61\29\3\35\36\4\4\4\
        \\46\46\4\46\3\42\43\4\4\4\
        \\24\24\3\24\3\50\51\4\4\4\
        \\53\63\41\53\3\35\36\4\4\4\
        \\30\25\65\4\3\15\16\4\4\4\
        \\47\40\4\4\3\27\38\4\4\4"
    lambdaTable =
        "\0\1\1\1\1\1\1\1\2\1\
        \\4\1\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\1\1\
        \\3\3\3\3\3\3\3\3\3\3\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\5\1\1\1\5\2\1\
        \\1\6\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\6\1\1\1\1\2\1\
        \\1\1\1\6\1\1\1\5\2\1\
        \\1\1\9\5\1\1\1\5\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\9\6\1\1\1\5\2\1\
        \\1\6\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\7\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\6\1\1\1\7\2\1\
        \\1\1\9\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\6\1\1\1\1\2\1\
        \\1\1\9\7\1\1\1\1\2\1\
        \\7\1\1\8\1\1\1\1\2\1\
        \\7\1\9\8\1\1\1\1\2\1\
        \\1\1\1\1\10\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\9\6\1\1\1\1\2\1\
        \\1\1\9\1\1\1\1\1\2\1\
        \\1\1\9\1\1\1\1\1\2\1\
        \\1\1\9\1\1\1\1\1\2\1\
        \\1\1\9\1\1\1\1\5\2\1\
        \\1\1\9\1\1\1\1\1\2\1\
        \\1\1\9\1\1\1\1\1\2\1\
        \\1\1\9\6\1\1\1\7\2\1\
        \\1\1\9\1\1\1\1\1\2\1\
        \\1\1\9\1\1\1\1\1\2\1\
        \\1\1\9\6\1\1\1\1\2\1\
        \\1\1\9\1\10\1\1\1\2\1\
        \\1\1\1\1\1\1\1\5\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\1\1\1\1\1\1\7\2\1\
        \\1\1\1\1\1\1\1\1\2\1\
        \\1\6\1\1\1\1\1\1\2\1\
        \\1\1\1\6\1\1\1\5\2\1\
        \\1\1\9\6\1\1\1\5\2\1\
        \\1\6\9\1\1\1\1\1\2\1\
        \\1\1\9\1\1\1\1\7\2\1\
        \\1\1\1\1\1\1\1\7\2\1\
        \\1\1\1\1\1\1\1\5\2\1\
        \\1\1\9\1\1\1\1\5\2\1\
        \\1\1\1\1\1\1\1\5\2\1\
        \\1\1\1\1\1\1\1\5\2\1\
        \\1\1\1\5\1\1\1\5\2\1\
        \\1\1\9\5\1\1\1\5\2\1"
