-- Generated by haal-gen. Do not edit manually.
module Haal.Models.DTLS.ScandiumV2V0V0EcdheCertReq
    ( ScandiumV2V0V0EcdheCertReqInput (..)
    , ScandiumV2V0V0EcdheCertReqOutput (..)
    , scandiumV2V0V0EcdheCertReq
    ) where

import Haal.Automaton.MealyAutomaton (MealyAutomaton, mkMealyAutomatonTable)

data ScandiumV2V0V0EcdheCertReqInput
    = In_ECDH_CLIENT_HELLO
    | In_ECDH_CLIENT_KEY_EXCHANGE
    | In_CHANGE_CIPHER_SPEC
    | In_FINISHED
    | In_APPLICATION
    | In_CERTIFICATE
    | In_EMPTY_CERTIFICATE
    | In_CERTIFICATE_VERIFY
    | In_Alert_WARNING_CLOSE_NOTIFY
    | In_Alert_FATAL_UNEXPECTED_MESSAGE
    deriving (Show, Eq, Ord, Enum, Bounded)

data ScandiumV2V0V0EcdheCertReqOutput
    = Out_HELLO_VERIFY_REQUEST
    | Out_TIMEOUT
    | Out_SERVER_HELLO_CERTIFICATE_ECDHE_SERVER_KEY_EXCHANGE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
    | Out_Alert_FATAL_INTERNAL_ERROR
    | Out_Alert_FATAL_HANDSHAKE_FAILURE
    | Out_Alert_WARNING_CLOSE_NOTIFY
    | Out_SERVER_HELLO_DONE
    | Out_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
    | Out_ECDHE_SERVER_KEY_EXCHANGE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
    | Out_CERTIFICATE_ECDHE_SERVER_KEY_EXCHANGE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
    | Out_CHANGE_CIPHER_SPEC_FINISHED
    | Out_Alert_WARNING_NO_RENEGOTIATION
    | Out_APPLICATION
    | Out_CHANGE_CIPHER_SPEC_FINISHED_APPLICATION
    deriving (Show, Eq, Ord, Enum, Bounded)

{- Transitions (state  input -> next state / output):
    0     In_ECDH_CLIENT_HELLO               -> 1 / Out_HELLO_VERIFY_REQUEST
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 2 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 2 / Out_TIMEOUT
          In_APPLICATION                     -> 0 / Out_TIMEOUT
          In_CERTIFICATE                     -> 2 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 2 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 2 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 0 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 0 / Out_TIMEOUT
    1     In_ECDH_CLIENT_HELLO               -> 3 / Out_SERVER_HELLO_CERTIFICATE_ECDHE_SERVER_KEY_EXCHANGE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 4 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 4 / Out_TIMEOUT
          In_APPLICATION                     -> 1 / Out_TIMEOUT
          In_CERTIFICATE                     -> 4 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 4 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    2     In_ECDH_CLIENT_HELLO               -> 2 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 2 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 2 / Out_TIMEOUT
          In_APPLICATION                     -> 2 / Out_TIMEOUT
          In_CERTIFICATE                     -> 2 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 2 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 2 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
    3     In_ECDH_CLIENT_HELLO               -> 8 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 9 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 9 / Out_Alert_FATAL_INTERNAL_ERROR
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 10 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 9 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_CERTIFICATE_VERIFY              -> 9 / Out_Alert_FATAL_INTERNAL_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
    4     In_ECDH_CLIENT_HELLO               -> 5 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 4 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 4 / Out_TIMEOUT
          In_APPLICATION                     -> 4 / Out_TIMEOUT
          In_CERTIFICATE                     -> 4 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 4 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    5     In_ECDH_CLIENT_HELLO               -> 6 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 4 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 4 / Out_Alert_FATAL_INTERNAL_ERROR
          In_APPLICATION                     -> 5 / Out_TIMEOUT
          In_CERTIFICATE                     -> 7 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_INTERNAL_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    6     In_ECDH_CLIENT_HELLO               -> 6 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 6 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 6 / Out_TIMEOUT
          In_APPLICATION                     -> 6 / Out_TIMEOUT
          In_CERTIFICATE                     -> 6 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 6 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 6 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    7     In_ECDH_CLIENT_HELLO               -> 6 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 15 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 4 / Out_Alert_FATAL_INTERNAL_ERROR
          In_APPLICATION                     -> 7 / Out_TIMEOUT
          In_CERTIFICATE                     -> 4 / Out_Alert_FATAL_INTERNAL_ERROR
          In_EMPTY_CERTIFICATE               -> 4 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_INTERNAL_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    8     In_ECDH_CLIENT_HELLO               -> 16 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 16 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 16 / Out_TIMEOUT
          In_APPLICATION                     -> 8 / Out_TIMEOUT
          In_CERTIFICATE                     -> 16 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 16 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 16 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 9 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 9 / Out_TIMEOUT
    9     In_ECDH_CLIENT_HELLO               -> 12 / Out_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 13 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 13 / Out_TIMEOUT
          In_APPLICATION                     -> 9 / Out_TIMEOUT
          In_CERTIFICATE                     -> 13 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 13 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 13 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 9 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 9 / Out_TIMEOUT
    10    In_ECDH_CLIENT_HELLO               -> 16 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 19 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 13 / Out_Alert_FATAL_INTERNAL_ERROR
          In_APPLICATION                     -> 10 / Out_TIMEOUT
          In_CERTIFICATE                     -> 13 / Out_Alert_FATAL_INTERNAL_ERROR
          In_EMPTY_CERTIFICATE               -> 13 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CERTIFICATE_VERIFY              -> 13 / Out_Alert_FATAL_INTERNAL_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 9 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 9 / Out_TIMEOUT
    11    In_ECDH_CLIENT_HELLO               -> 12 / Out_SERVER_HELLO_DONE
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 9 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 9 / Out_TIMEOUT
          In_APPLICATION                     -> 11 / Out_TIMEOUT
          In_CERTIFICATE                     -> 9 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 9 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 9 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
    12    In_ECDH_CLIENT_HELLO               -> 8 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 9 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 9 / Out_Alert_FATAL_INTERNAL_ERROR
          In_APPLICATION                     -> 12 / Out_TIMEOUT
          In_CERTIFICATE                     -> 29 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 9 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_CERTIFICATE_VERIFY              -> 9 / Out_Alert_FATAL_INTERNAL_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 11 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 11 / Out_TIMEOUT
    13    In_ECDH_CLIENT_HELLO               -> 12 / Out_ECDHE_SERVER_KEY_EXCHANGE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 14 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 14 / Out_TIMEOUT
          In_APPLICATION                     -> 13 / Out_TIMEOUT
          In_CERTIFICATE                     -> 14 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 14 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 14 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 13 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 13 / Out_TIMEOUT
    14    In_ECDH_CLIENT_HELLO               -> 12 / Out_CERTIFICATE_ECDHE_SERVER_KEY_EXCHANGE_CERTIFICATE_REQUEST_SERVER_HELLO_DONE
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 1 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_TIMEOUT
          In_APPLICATION                     -> 14 / Out_TIMEOUT
          In_CERTIFICATE                     -> 1 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 1 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 1 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 14 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 14 / Out_TIMEOUT
    15    In_ECDH_CLIENT_HELLO               -> 6 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 4 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 4 / Out_Alert_FATAL_INTERNAL_ERROR
          In_APPLICATION                     -> 15 / Out_TIMEOUT
          In_CERTIFICATE                     -> 4 / Out_Alert_FATAL_INTERNAL_ERROR
          In_EMPTY_CERTIFICATE               -> 4 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CERTIFICATE_VERIFY              -> 4 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    16    In_ECDH_CLIENT_HELLO               -> 17 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 17 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 17 / Out_TIMEOUT
          In_APPLICATION                     -> 16 / Out_TIMEOUT
          In_CERTIFICATE                     -> 17 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 17 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 17 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 13 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 13 / Out_TIMEOUT
    17    In_ECDH_CLIENT_HELLO               -> 18 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 18 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 18 / Out_TIMEOUT
          In_APPLICATION                     -> 17 / Out_TIMEOUT
          In_CERTIFICATE                     -> 18 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 18 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 18 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 14 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 14 / Out_TIMEOUT
    18    In_ECDH_CLIENT_HELLO               -> 6 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 6 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 6 / Out_TIMEOUT
          In_APPLICATION                     -> 18 / Out_TIMEOUT
          In_CERTIFICATE                     -> 6 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 6 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 6 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    19    In_ECDH_CLIENT_HELLO               -> 17 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 14 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 14 / Out_Alert_FATAL_INTERNAL_ERROR
          In_APPLICATION                     -> 19 / Out_TIMEOUT
          In_CERTIFICATE                     -> 14 / Out_Alert_FATAL_INTERNAL_ERROR
          In_EMPTY_CERTIFICATE               -> 14 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CERTIFICATE_VERIFY              -> 20 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 13 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 13 / Out_TIMEOUT
    20    In_ECDH_CLIENT_HELLO               -> 21 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 1 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CHANGE_CIPHER_SPEC              -> 22 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_Alert_FATAL_INTERNAL_ERROR
          In_APPLICATION                     -> 20 / Out_TIMEOUT
          In_CERTIFICATE                     -> 1 / Out_Alert_FATAL_INTERNAL_ERROR
          In_EMPTY_CERTIFICATE               -> 1 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CERTIFICATE_VERIFY              -> 1 / Out_Alert_FATAL_INTERNAL_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 14 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 14 / Out_TIMEOUT
    21    In_ECDH_CLIENT_HELLO               -> 26 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 27 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 28 / Out_TIMEOUT
          In_FINISHED                        -> 27 / Out_TIMEOUT
          In_APPLICATION                     -> 21 / Out_TIMEOUT
          In_CERTIFICATE                     -> 27 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 27 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 27 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    22    In_ECDH_CLIENT_HELLO               -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_FINISHED                        -> 23 / Out_CHANGE_CIPHER_SPEC_FINISHED
          In_APPLICATION                     -> 24 / Out_TIMEOUT
          In_CERTIFICATE                     -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_EMPTY_CERTIFICATE               -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CERTIFICATE_VERIFY              -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
    23    In_ECDH_CLIENT_HELLO               -> 23 / Out_Alert_WARNING_NO_RENEGOTIATION
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 23 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_FINISHED                        -> 23 / Out_TIMEOUT
          In_APPLICATION                     -> 25 / Out_APPLICATION
          In_CERTIFICATE                     -> 23 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 23 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 23 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
    24    In_ECDH_CLIENT_HELLO               -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_FINISHED                        -> 25 / Out_CHANGE_CIPHER_SPEC_FINISHED_APPLICATION
          In_APPLICATION                     -> 24 / Out_TIMEOUT
          In_CERTIFICATE                     -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_EMPTY_CERTIFICATE               -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CERTIFICATE_VERIFY              -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
    25    In_ECDH_CLIENT_HELLO               -> 25 / Out_Alert_WARNING_NO_RENEGOTIATION
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 25 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 25 / Out_TIMEOUT
          In_APPLICATION                     -> 25 / Out_APPLICATION
          In_CERTIFICATE                     -> 25 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 25 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 25 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
    26    In_ECDH_CLIENT_HELLO               -> 26 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 27 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 28 / Out_TIMEOUT
          In_FINISHED                        -> 27 / Out_TIMEOUT
          In_APPLICATION                     -> 26 / Out_TIMEOUT
          In_CERTIFICATE                     -> 27 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 27 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 27 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    27    In_ECDH_CLIENT_HELLO               -> 27 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 27 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_FINISHED                        -> 27 / Out_TIMEOUT
          In_APPLICATION                     -> 27 / Out_TIMEOUT
          In_CERTIFICATE                     -> 27 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 27 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 27 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 4 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 4 / Out_TIMEOUT
    28    In_ECDH_CLIENT_HELLO               -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 28 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_FINISHED                        -> 28 / Out_TIMEOUT
          In_APPLICATION                     -> 28 / Out_TIMEOUT
          In_CERTIFICATE                     -> 28 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 28 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 28 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
    29    In_ECDH_CLIENT_HELLO               -> 16 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 30 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 13 / Out_Alert_FATAL_INTERNAL_ERROR
          In_APPLICATION                     -> 29 / Out_TIMEOUT
          In_CERTIFICATE                     -> 13 / Out_Alert_FATAL_INTERNAL_ERROR
          In_EMPTY_CERTIFICATE               -> 13 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CERTIFICATE_VERIFY              -> 13 / Out_Alert_FATAL_INTERNAL_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 9 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 9 / Out_TIMEOUT
    30    In_ECDH_CLIENT_HELLO               -> 17 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 14 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 14 / Out_Alert_FATAL_INTERNAL_ERROR
          In_APPLICATION                     -> 30 / Out_TIMEOUT
          In_CERTIFICATE                     -> 14 / Out_Alert_FATAL_INTERNAL_ERROR
          In_EMPTY_CERTIFICATE               -> 14 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CERTIFICATE_VERIFY              -> 14 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_Alert_WARNING_CLOSE_NOTIFY      -> 13 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 13 / Out_TIMEOUT
-}
scandiumV2V0V0EcdheCertReq :: MealyAutomaton Int ScandiumV2V0V0EcdheCertReqInput ScandiumV2V0V0EcdheCertReqOutput
scandiumV2V0V0EcdheCertReq =
    case mkMealyAutomatonTable 31 0 deltaTable lambdaTable of
        Right m -> m
        Left err -> error ("haal-gen: invalid transition table: " ++ err)
  where
    deltaTable =
        "\1\2\2\2\0\2\2\2\0\0\
        \\3\4\2\4\1\4\4\4\1\1\
        \\2\2\2\2\2\2\2\2\2\2\
        \\8\9\2\9\3\10\9\9\11\11\
        \\5\4\2\4\4\4\4\4\4\4\
        \\6\4\2\4\5\7\4\4\4\4\
        \\6\6\2\6\6\6\6\6\4\4\
        \\6\15\2\4\7\4\4\4\4\4\
        \\16\16\2\16\8\16\16\16\9\9\
        \\12\13\2\13\9\13\13\13\9\9\
        \\16\19\2\13\10\13\13\13\9\9\
        \\12\9\2\9\11\9\9\9\11\11\
        \\8\9\2\9\12\29\9\9\11\11\
        \\12\14\2\14\13\14\14\14\13\13\
        \\12\1\2\1\14\1\1\1\14\14\
        \\6\4\2\4\15\4\4\4\4\4\
        \\17\17\2\17\16\17\17\17\13\13\
        \\18\18\2\18\17\18\18\18\14\14\
        \\6\6\2\6\18\6\6\6\1\1\
        \\17\14\2\14\19\14\14\20\13\13\
        \\21\1\22\1\20\1\1\1\14\14\
        \\26\27\28\27\21\27\27\27\1\1\
        \\2\2\2\23\24\2\2\2\2\2\
        \\23\23\2\23\25\23\23\23\2\2\
        \\2\2\2\25\24\2\2\2\2\2\
        \\25\25\2\25\25\25\25\25\2\2\
        \\26\27\28\27\26\27\27\27\4\4\
        \\27\27\2\27\27\27\27\27\4\4\
        \\2\28\2\28\28\28\28\28\2\2\
        \\16\30\2\13\29\13\13\13\9\9\
        \\17\14\2\14\30\14\14\14\13\13"
    lambdaTable =
        "\0\1\1\1\1\1\1\1\1\1\
        \\2\1\1\1\1\1\1\1\1\1\
        \\1\1\1\1\1\1\1\1\1\1\
        \\1\3\1\3\1\1\4\3\5\1\
        \\1\1\1\1\1\1\1\1\1\1\
        \\1\3\1\3\1\1\4\3\5\1\
        \\1\1\1\1\1\1\1\1\5\1\
        \\1\1\1\3\1\3\3\3\5\1\
        \\1\1\1\1\1\1\1\1\5\1\
        \\7\1\1\1\1\1\1\1\1\1\
        \\1\1\1\3\1\3\3\3\5\1\
        \\6\1\1\1\1\1\1\1\1\1\
        \\1\3\1\3\1\1\4\3\5\1\
        \\8\1\1\1\1\1\1\1\1\1\
        \\9\1\1\1\1\1\1\1\1\1\
        \\1\3\1\3\1\3\3\4\5\1\
        \\1\1\1\1\1\1\1\1\5\1\
        \\1\1\1\1\1\1\1\1\5\1\
        \\1\1\1\1\1\1\1\1\5\1\
        \\1\3\1\3\1\3\3\1\5\1\
        \\1\3\1\3\1\3\3\3\5\1\
        \\1\1\1\1\1\1\1\1\5\1\
        \\3\3\3\10\1\3\3\3\5\1\
        \\11\1\3\1\12\1\1\1\5\1\
        \\3\3\3\13\1\3\3\3\5\1\
        \\11\1\1\1\12\1\1\1\5\1\
        \\1\1\1\1\1\1\1\1\5\1\
        \\1\1\4\1\1\1\1\1\5\1\
        \\3\1\3\1\1\1\1\1\5\1\
        \\1\1\1\3\1\3\3\3\5\1\
        \\1\3\1\3\1\3\3\4\5\1"
