-- Generated by haal-gen. Do not edit manually.
module Haal.Models.DTLS.ScandiumLatestEcdheCertNone
    ( ScandiumLatestEcdheCertNoneInput (..)
    , ScandiumLatestEcdheCertNoneOutput (..)
    , scandiumLatestEcdheCertNone
    ) where

import Haal.Automaton.MealyAutomaton (MealyAutomaton, mkMealyAutomatonTable)

data ScandiumLatestEcdheCertNoneInput
    = In_ECDH_CLIENT_HELLO
    | In_ECDH_CLIENT_KEY_EXCHANGE
    | In_CHANGE_CIPHER_SPEC
    | In_FINISHED
    | In_APPLICATION
    | In_CERTIFICATE
    | In_EMPTY_CERTIFICATE
    | In_CERTIFICATE_VERIFY
    | In_Alert_WARNING_CLOSE_NOTIFY
    | In_Alert_FATAL_UNEXPECTED_MESSAGE
    deriving (Show, Eq, Ord, Enum, Bounded)

data ScandiumLatestEcdheCertNoneOutput
    = Out_HELLO_VERIFY_REQUEST
    | Out_TIMEOUT
    | Out_SERVER_HELLO_CERTIFICATE_ECDHE_SERVER_KEY_EXCHANGE_SERVER_HELLO_DONE
    | Out_Alert_FATAL_INTERNAL_ERROR
    | Out_Alert_WARNING_CLOSE_NOTIFY
    | Out_CHANGE_CIPHER_SPEC_FINISHED
    | Out_Alert_WARNING_NO_RENEGOTIATION
    | Out_APPLICATION
    | Out_Alert_FATAL_HANDSHAKE_FAILURE
    | Out_CHANGE_CIPHER_SPEC_FINISHED_APPLICATION
    deriving (Show, Eq, Ord, Enum, Bounded)

{- Transitions (state  input -> next state / output):
    0     In_ECDH_CLIENT_HELLO               -> 1 / Out_HELLO_VERIFY_REQUEST
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 0 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 0 / Out_TIMEOUT
          In_APPLICATION                     -> 0 / Out_TIMEOUT
          In_CERTIFICATE                     -> 0 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 0 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 0 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 0 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 0 / Out_TIMEOUT
    1     In_ECDH_CLIENT_HELLO               -> 3 / Out_SERVER_HELLO_CERTIFICATE_ECDHE_SERVER_KEY_EXCHANGE_SERVER_HELLO_DONE
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 1 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_TIMEOUT
          In_APPLICATION                     -> 1 / Out_TIMEOUT
          In_CERTIFICATE                     -> 1 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 1 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 1 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    2     In_ECDH_CLIENT_HELLO               -> 2 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 2 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 2 / Out_TIMEOUT
          In_APPLICATION                     -> 2 / Out_TIMEOUT
          In_CERTIFICATE                     -> 2 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 2 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 2 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_TIMEOUT
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
    3     In_ECDH_CLIENT_HELLO               -> 4 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 5 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_Alert_FATAL_INTERNAL_ERROR
          In_APPLICATION                     -> 3 / Out_TIMEOUT
          In_CERTIFICATE                     -> 1 / Out_Alert_FATAL_INTERNAL_ERROR
          In_EMPTY_CERTIFICATE               -> 1 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CERTIFICATE_VERIFY              -> 1 / Out_Alert_FATAL_INTERNAL_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    4     In_ECDH_CLIENT_HELLO               -> 4 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 4 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 4 / Out_TIMEOUT
          In_APPLICATION                     -> 4 / Out_TIMEOUT
          In_CERTIFICATE                     -> 4 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 4 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 4 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    5     In_ECDH_CLIENT_HELLO               -> 6 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 1 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CHANGE_CIPHER_SPEC              -> 7 / Out_TIMEOUT
          In_FINISHED                        -> 1 / Out_Alert_FATAL_INTERNAL_ERROR
          In_APPLICATION                     -> 5 / Out_TIMEOUT
          In_CERTIFICATE                     -> 1 / Out_Alert_FATAL_INTERNAL_ERROR
          In_EMPTY_CERTIFICATE               -> 1 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CERTIFICATE_VERIFY              -> 1 / Out_Alert_FATAL_INTERNAL_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    6     In_ECDH_CLIENT_HELLO               -> 6 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 11 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 12 / Out_TIMEOUT
          In_FINISHED                        -> 11 / Out_TIMEOUT
          In_APPLICATION                     -> 6 / Out_TIMEOUT
          In_CERTIFICATE                     -> 11 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 11 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 11 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    7     In_ECDH_CLIENT_HELLO               -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_FINISHED                        -> 8 / Out_CHANGE_CIPHER_SPEC_FINISHED
          In_APPLICATION                     -> 9 / Out_TIMEOUT
          In_CERTIFICATE                     -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_EMPTY_CERTIFICATE               -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CERTIFICATE_VERIFY              -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
    8     In_ECDH_CLIENT_HELLO               -> 8 / Out_Alert_WARNING_NO_RENEGOTIATION
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 8 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_FINISHED                        -> 8 / Out_TIMEOUT
          In_APPLICATION                     -> 10 / Out_APPLICATION
          In_CERTIFICATE                     -> 8 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 8 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 8 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
    9     In_ECDH_CLIENT_HELLO               -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_FINISHED                        -> 10 / Out_CHANGE_CIPHER_SPEC_FINISHED_APPLICATION
          In_APPLICATION                     -> 9 / Out_TIMEOUT
          In_CERTIFICATE                     -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_EMPTY_CERTIFICATE               -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_CERTIFICATE_VERIFY              -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
    10    In_ECDH_CLIENT_HELLO               -> 10 / Out_Alert_WARNING_NO_RENEGOTIATION
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 10 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_TIMEOUT
          In_FINISHED                        -> 10 / Out_TIMEOUT
          In_APPLICATION                     -> 10 / Out_APPLICATION
          In_CERTIFICATE                     -> 10 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 10 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 10 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
    11    In_ECDH_CLIENT_HELLO               -> 11 / Out_TIMEOUT
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 11 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_Alert_FATAL_HANDSHAKE_FAILURE
          In_FINISHED                        -> 11 / Out_TIMEOUT
          In_APPLICATION                     -> 11 / Out_TIMEOUT
          In_CERTIFICATE                     -> 11 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 11 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 11 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 1 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 1 / Out_TIMEOUT
    12    In_ECDH_CLIENT_HELLO               -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_ECDH_CLIENT_KEY_EXCHANGE        -> 12 / Out_TIMEOUT
          In_CHANGE_CIPHER_SPEC              -> 2 / Out_Alert_FATAL_INTERNAL_ERROR
          In_FINISHED                        -> 12 / Out_TIMEOUT
          In_APPLICATION                     -> 12 / Out_TIMEOUT
          In_CERTIFICATE                     -> 12 / Out_TIMEOUT
          In_EMPTY_CERTIFICATE               -> 12 / Out_TIMEOUT
          In_CERTIFICATE_VERIFY              -> 12 / Out_TIMEOUT
          In_Alert_WARNING_CLOSE_NOTIFY      -> 2 / Out_Alert_WARNING_CLOSE_NOTIFY
          In_Alert_FATAL_UNEXPECTED_MESSAGE  -> 2 / Out_TIMEOUT
-}
scandiumLatestEcdheCertNone :: MealyAutomaton Int ScandiumLatestEcdheCertNoneInput ScandiumLatestEcdheCertNoneOutput
scandiumLatestEcdheCertNone =
    case mkMealyAutomatonTable 13 0 deltaTable lambdaTable of
        Right m -> m
        Left err -> error ("haal-gen: invalid transition table: " ++ err)
  where
    deltaTable =
        "\1\0\2\0\0\0\0\0\0\0\
        \\3\1\2\1\1\1\1\1\1\1\
        \\2\2\2\2\2\2\2\2\2\2\
        \\4\5\2\1\3\1\1\1\1\1\
        \\4\4\2\4\4\4\4\4\1\1\
        \\6\1\7\1\5\1\1\1\1\1\
        \\6\11\12\11\6\11\11\11\1\1\
        \\2\2\2\8\9\2\2\2\2\2\
        \\8\8\2\8\10\8\8\8\2\2\
        \\2\2\2\10\9\2\2\2\2\2\
        \\10\10\2\10\10\10\10\10\2\2\
        \\11\11\2\11\11\11\11\11\1\1\
        \\2\12\2\12\12\12\12\12\2\2"
    lambdaTable =
        "\0\1\1\1\1\1\1\1\1\1\
        \\2\1\1\1\1\1\1\1\1\1\
        \\1\1\1\1\1\1\1\1\1\1\
        \\1\1\1\3\1\3\3\3\4\1\
        \\1\1\1\1\1\1\1\1\4\1\
        \\1\3\1\3\1\3\3\3\4\1\
        \\1\1\1\1\1\1\1\1\4\1\
        \\3\3\3\5\1\3\3\3\4\1\
        \\6\1\3\1\7\1\1\1\4\1\
        \\3\3\3\9\1\3\3\3\4\1\
        \\6\1\1\1\7\1\1\1\4\1\
        \\1\1\8\1\1\1\1\1\4\1\
        \\3\1\3\1\1\1\1\1\4\1"
