-- Generated by haal-gen. Do not edit manually.
module Haal.Models.MQTT.EmqttTwoClient
    ( EmqttTwoClientInput (..)
    , EmqttTwoClientOutput (..)
    , emqttTwoClient
    ) where

import qualified Data.Set as Set
import Haal.Automaton.MealyAutomaton (MealyAutomaton, mkMealyAutomaton)

data EmqttTwoClientInput
    = In_ConnectC2
    | In_ConnectC1WithWill
    | In_PublishQoS0C2
    | In_PublishQoS1C1
    | In_SubscribeC1
    | In_UnSubScribeC1
    | In_SubscribeC2
    | In_UnSubScribeC2
    | In_DisconnectTCPC1
    deriving (Show, Eq, Ord, Enum, Bounded)

data EmqttTwoClientOutput
    = Out_C1_ConnectionClosed_client_close___c2_ConnAck
    | Out_C1_ConnAck__c2_ConnectionClosed_client_close
    | Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_client_close
    | Out_Empty__c2_ConnAck
    | Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_client_close
    | Out_Empty__c2_ConnectionClosed_client_close
    | Out_C1_PubAck__c2_ConnectionClosed_client_close
    | Out_C1_SubAck__Pub_c1_my_topic_bye___c2_ConnectionClosed_client_close
    | Out_C1_UnSubAck__c2_ConnectionClosed_client_close
    | Out_Empty__c2_ConnectionClosed_eof_stream
    | Out_C1_ConnectionClosed_eof_stream___Empty
    | Out_Empty__Empty
    | Out_C1_PubAck__Empty
    | Out_C1_SubAck__Pub_c1_my_topic_bye___Empty
    | Out_C1_UnSubAck__Empty
    | Out_Empty__c2_SubAck__Pub_c2_my_topic_bye
    | Out_Empty__c2_UnSubAck
    | Out_C1_ConnectionClosed_client_close___Empty
    | Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_eof_stream
    | Out_C1_ConnAck__Empty
    | Out_C1_ConnectionClosed_client_close___c2_SubAck__Pub_c2_my_topic_bye
    | Out_C1_ConnectionClosed_client_close___c2_UnSubAck
    | Out_C1_ConnectionClosed_eof_stream___c2_ConnAck
    | Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_eof_stream
    | Out_C1_ConnectionClosed_eof_stream___c2_SubAck__Pub_c2_my_topic_bye
    | Out_C1_ConnectionClosed_eof_stream___c2_UnSubAck
    | Out_C1_ConnectionClosed_client_close___Pub_c2_my_topic_messageQos0
    | Out_C1_ConnectionClosed_client_close___c2_SubAck
    | Out_C1_ConnAck__c2_ConnectionClosed_eof_stream
    | Out_C1_ConnectionClosed_eof_stream___Pub_c2_my_topic_bye
    | Out_Empty__Pub_c2_my_topic_messageQos0
    | Out_C1_PubAck__Pub_c2_my_topic_messageQos1
    | Out_Empty__c2_SubAck
    | Out_C1_ConnectionClosed_client_close___Pub_c2_my_topic_bye
    | Out_C1_ConnectionClosed_eof_stream___Pub_c2_my_topic_messageQos0
    | Out_C1_ConnectionClosed_eof_stream___c2_SubAck
    | Out_C1_PubAck__c2_ConnectionClosed_eof_stream
    | Out_C1_SubAck__Pub_c1_my_topic_bye___c2_ConnectionClosed_eof_stream
    | Out_C1_UnSubAck__c2_ConnectionClosed_eof_stream
    | Out_Pub_c1_my_topic_messageQos0___Empty
    | Out_Pub_c1_my_topic_messageQos1___c1_PubAck__Empty
    | Out_C1_SubAck__Empty
    | Out_Pub_c1_my_topic_messageQos0___Pub_c2_my_topic_messageQos0
    | Out_Pub_c1_my_topic_messageQos1___c1_PubAck__Pub_c2_my_topic_messageQos1
    | Out_Pub_c1_my_topic_messageQos1___c1_PubAck__c2_ConnectionClosed_eof_stream
    | Out_C1_SubAck__c2_ConnectionClosed_eof_stream
    | Out_Pub_c1_my_topic_messageQos1___c1_PubAck__c2_ConnectionClosed_client_close
    | Out_C1_SubAck__c2_ConnectionClosed_client_close
    deriving (Show, Eq, Ord, Enum, Bounded)

emqttTwoClient :: MealyAutomaton Int EmqttTwoClientInput EmqttTwoClientOutput
emqttTwoClient = mkMealyAutomaton delta lambda (Set.fromList [0..15]) 0
  where
    delta 0 In_ConnectC2 = 1
    delta 0 In_ConnectC1WithWill = 2
    delta 0 In_PublishQoS0C2 = 0
    delta 0 In_PublishQoS1C1 = 0
    delta 0 In_SubscribeC1 = 0
    delta 0 In_UnSubScribeC1 = 0
    delta 0 In_SubscribeC2 = 0
    delta 0 In_UnSubScribeC2 = 0
    delta 0 In_DisconnectTCPC1 = 0
    delta 2 In_ConnectC2 = 3
    delta 2 In_ConnectC1WithWill = 4
    delta 2 In_PublishQoS0C2 = 2
    delta 2 In_PublishQoS1C1 = 2
    delta 2 In_SubscribeC1 = 5
    delta 2 In_UnSubScribeC1 = 2
    delta 2 In_SubscribeC2 = 2
    delta 2 In_UnSubScribeC2 = 2
    delta 2 In_DisconnectTCPC1 = 0
    delta 3 In_ConnectC2 = 6
    delta 3 In_ConnectC1WithWill = 7
    delta 3 In_PublishQoS0C2 = 3
    delta 3 In_PublishQoS1C1 = 3
    delta 3 In_SubscribeC1 = 8
    delta 3 In_UnSubScribeC1 = 3
    delta 3 In_SubscribeC2 = 9
    delta 3 In_UnSubScribeC2 = 3
    delta 3 In_DisconnectTCPC1 = 1
    delta 1 In_ConnectC2 = 10
    delta 1 In_ConnectC1WithWill = 3
    delta 1 In_PublishQoS0C2 = 1
    delta 1 In_PublishQoS1C1 = 1
    delta 1 In_SubscribeC1 = 1
    delta 1 In_UnSubScribeC1 = 1
    delta 1 In_SubscribeC2 = 11
    delta 1 In_UnSubScribeC2 = 1
    delta 1 In_DisconnectTCPC1 = 1
    delta 4 In_ConnectC2 = 7
    delta 4 In_ConnectC1WithWill = 2
    delta 4 In_PublishQoS0C2 = 4
    delta 4 In_PublishQoS1C1 = 4
    delta 4 In_SubscribeC1 = 4
    delta 4 In_UnSubScribeC1 = 4
    delta 4 In_SubscribeC2 = 4
    delta 4 In_UnSubScribeC2 = 4
    delta 4 In_DisconnectTCPC1 = 0
    delta 7 In_ConnectC2 = 12
    delta 7 In_ConnectC1WithWill = 3
    delta 7 In_PublishQoS0C2 = 7
    delta 7 In_PublishQoS1C1 = 7
    delta 7 In_SubscribeC1 = 7
    delta 7 In_UnSubScribeC1 = 7
    delta 7 In_SubscribeC2 = 13
    delta 7 In_UnSubScribeC2 = 7
    delta 7 In_DisconnectTCPC1 = 1
    delta 11 In_ConnectC2 = 10
    delta 11 In_ConnectC1WithWill = 9
    delta 11 In_PublishQoS0C2 = 11
    delta 11 In_PublishQoS1C1 = 11
    delta 11 In_SubscribeC1 = 11
    delta 11 In_UnSubScribeC1 = 11
    delta 11 In_SubscribeC2 = 11
    delta 11 In_UnSubScribeC2 = 1
    delta 11 In_DisconnectTCPC1 = 11
    delta 10 In_ConnectC2 = 1
    delta 10 In_ConnectC1WithWill = 6
    delta 10 In_PublishQoS0C2 = 10
    delta 10 In_PublishQoS1C1 = 10
    delta 10 In_SubscribeC1 = 10
    delta 10 In_UnSubScribeC1 = 10
    delta 10 In_SubscribeC2 = 10
    delta 10 In_UnSubScribeC2 = 10
    delta 10 In_DisconnectTCPC1 = 10
    delta 9 In_ConnectC2 = 6
    delta 9 In_ConnectC1WithWill = 13
    delta 9 In_PublishQoS0C2 = 9
    delta 9 In_PublishQoS1C1 = 9
    delta 9 In_SubscribeC1 = 14
    delta 9 In_UnSubScribeC1 = 9
    delta 9 In_SubscribeC2 = 9
    delta 9 In_UnSubScribeC2 = 3
    delta 9 In_DisconnectTCPC1 = 11
    delta 13 In_ConnectC2 = 12
    delta 13 In_ConnectC1WithWill = 9
    delta 13 In_PublishQoS0C2 = 13
    delta 13 In_PublishQoS1C1 = 13
    delta 13 In_SubscribeC1 = 13
    delta 13 In_UnSubScribeC1 = 13
    delta 13 In_SubscribeC2 = 13
    delta 13 In_UnSubScribeC2 = 7
    delta 13 In_DisconnectTCPC1 = 11
    delta 6 In_ConnectC2 = 3
    delta 6 In_ConnectC1WithWill = 12
    delta 6 In_PublishQoS0C2 = 6
    delta 6 In_PublishQoS1C1 = 6
    delta 6 In_SubscribeC1 = 15
    delta 6 In_UnSubScribeC1 = 6
    delta 6 In_SubscribeC2 = 6
    delta 6 In_UnSubScribeC2 = 6
    delta 6 In_DisconnectTCPC1 = 10
    delta 8 In_ConnectC2 = 15
    delta 8 In_ConnectC1WithWill = 7
    delta 8 In_PublishQoS0C2 = 8
    delta 8 In_PublishQoS1C1 = 8
    delta 8 In_SubscribeC1 = 8
    delta 8 In_UnSubScribeC1 = 3
    delta 8 In_SubscribeC2 = 14
    delta 8 In_UnSubScribeC2 = 8
    delta 8 In_DisconnectTCPC1 = 1
    delta 12 In_ConnectC2 = 7
    delta 12 In_ConnectC1WithWill = 6
    delta 12 In_PublishQoS0C2 = 12
    delta 12 In_PublishQoS1C1 = 12
    delta 12 In_SubscribeC1 = 12
    delta 12 In_UnSubScribeC1 = 12
    delta 12 In_SubscribeC2 = 12
    delta 12 In_UnSubScribeC2 = 12
    delta 12 In_DisconnectTCPC1 = 10
    delta 14 In_ConnectC2 = 15
    delta 14 In_ConnectC1WithWill = 13
    delta 14 In_PublishQoS0C2 = 14
    delta 14 In_PublishQoS1C1 = 14
    delta 14 In_SubscribeC1 = 14
    delta 14 In_UnSubScribeC1 = 9
    delta 14 In_SubscribeC2 = 14
    delta 14 In_UnSubScribeC2 = 8
    delta 14 In_DisconnectTCPC1 = 11
    delta 15 In_ConnectC2 = 8
    delta 15 In_ConnectC1WithWill = 12
    delta 15 In_PublishQoS0C2 = 15
    delta 15 In_PublishQoS1C1 = 15
    delta 15 In_SubscribeC1 = 15
    delta 15 In_UnSubScribeC1 = 6
    delta 15 In_SubscribeC2 = 15
    delta 15 In_UnSubScribeC2 = 15
    delta 15 In_DisconnectTCPC1 = 10
    delta 5 In_ConnectC2 = 8
    delta 5 In_ConnectC1WithWill = 4
    delta 5 In_PublishQoS0C2 = 5
    delta 5 In_PublishQoS1C1 = 5
    delta 5 In_SubscribeC1 = 5
    delta 5 In_UnSubScribeC1 = 2
    delta 5 In_SubscribeC2 = 5
    delta 5 In_UnSubScribeC2 = 5
    delta 5 In_DisconnectTCPC1 = 0
    delta _ _ = error "haal-gen: undefined transition"
    lambda 0 In_ConnectC2 = Out_C1_ConnectionClosed_client_close___c2_ConnAck
    lambda 0 In_ConnectC1WithWill = Out_C1_ConnAck__c2_ConnectionClosed_client_close
    lambda 0 In_PublishQoS0C2 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_client_close
    lambda 0 In_PublishQoS1C1 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_client_close
    lambda 0 In_SubscribeC1 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_client_close
    lambda 0 In_UnSubScribeC1 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_client_close
    lambda 0 In_SubscribeC2 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_client_close
    lambda 0 In_UnSubScribeC2 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_client_close
    lambda 0 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_client_close
    lambda 2 In_ConnectC2 = Out_Empty__c2_ConnAck
    lambda 2 In_ConnectC1WithWill = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_client_close
    lambda 2 In_PublishQoS0C2 = Out_Empty__c2_ConnectionClosed_client_close
    lambda 2 In_PublishQoS1C1 = Out_C1_PubAck__c2_ConnectionClosed_client_close
    lambda 2 In_SubscribeC1 = Out_C1_SubAck__Pub_c1_my_topic_bye___c2_ConnectionClosed_client_close
    lambda 2 In_UnSubScribeC1 = Out_C1_UnSubAck__c2_ConnectionClosed_client_close
    lambda 2 In_SubscribeC2 = Out_Empty__c2_ConnectionClosed_client_close
    lambda 2 In_UnSubScribeC2 = Out_Empty__c2_ConnectionClosed_client_close
    lambda 2 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_client_close
    lambda 3 In_ConnectC2 = Out_Empty__c2_ConnectionClosed_eof_stream
    lambda 3 In_ConnectC1WithWill = Out_C1_ConnectionClosed_eof_stream___Empty
    lambda 3 In_PublishQoS0C2 = Out_Empty__Empty
    lambda 3 In_PublishQoS1C1 = Out_C1_PubAck__Empty
    lambda 3 In_SubscribeC1 = Out_C1_SubAck__Pub_c1_my_topic_bye___Empty
    lambda 3 In_UnSubScribeC1 = Out_C1_UnSubAck__Empty
    lambda 3 In_SubscribeC2 = Out_Empty__c2_SubAck__Pub_c2_my_topic_bye
    lambda 3 In_UnSubScribeC2 = Out_Empty__c2_UnSubAck
    lambda 3 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___Empty
    lambda 1 In_ConnectC2 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_eof_stream
    lambda 1 In_ConnectC1WithWill = Out_C1_ConnAck__Empty
    lambda 1 In_PublishQoS0C2 = Out_C1_ConnectionClosed_client_close___Empty
    lambda 1 In_PublishQoS1C1 = Out_C1_ConnectionClosed_client_close___Empty
    lambda 1 In_SubscribeC1 = Out_C1_ConnectionClosed_client_close___Empty
    lambda 1 In_UnSubScribeC1 = Out_C1_ConnectionClosed_client_close___Empty
    lambda 1 In_SubscribeC2 = Out_C1_ConnectionClosed_client_close___c2_SubAck__Pub_c2_my_topic_bye
    lambda 1 In_UnSubScribeC2 = Out_C1_ConnectionClosed_client_close___c2_UnSubAck
    lambda 1 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___Empty
    lambda 4 In_ConnectC2 = Out_C1_ConnectionClosed_eof_stream___c2_ConnAck
    lambda 4 In_ConnectC1WithWill = Out_C1_ConnAck__c2_ConnectionClosed_client_close
    lambda 4 In_PublishQoS0C2 = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_client_close
    lambda 4 In_PublishQoS1C1 = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_client_close
    lambda 4 In_SubscribeC1 = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_client_close
    lambda 4 In_UnSubScribeC1 = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_client_close
    lambda 4 In_SubscribeC2 = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_client_close
    lambda 4 In_UnSubScribeC2 = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_client_close
    lambda 4 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_client_close
    lambda 7 In_ConnectC2 = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_eof_stream
    lambda 7 In_ConnectC1WithWill = Out_C1_ConnAck__Empty
    lambda 7 In_PublishQoS0C2 = Out_C1_ConnectionClosed_eof_stream___Empty
    lambda 7 In_PublishQoS1C1 = Out_C1_ConnectionClosed_eof_stream___Empty
    lambda 7 In_SubscribeC1 = Out_C1_ConnectionClosed_eof_stream___Empty
    lambda 7 In_UnSubScribeC1 = Out_C1_ConnectionClosed_eof_stream___Empty
    lambda 7 In_SubscribeC2 = Out_C1_ConnectionClosed_eof_stream___c2_SubAck__Pub_c2_my_topic_bye
    lambda 7 In_UnSubScribeC2 = Out_C1_ConnectionClosed_eof_stream___c2_UnSubAck
    lambda 7 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___Empty
    lambda 11 In_ConnectC2 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_eof_stream
    lambda 11 In_ConnectC1WithWill = Out_C1_ConnAck__Empty
    lambda 11 In_PublishQoS0C2 = Out_C1_ConnectionClosed_client_close___Pub_c2_my_topic_messageQos0
    lambda 11 In_PublishQoS1C1 = Out_C1_ConnectionClosed_client_close___Empty
    lambda 11 In_SubscribeC1 = Out_C1_ConnectionClosed_client_close___Empty
    lambda 11 In_UnSubScribeC1 = Out_C1_ConnectionClosed_client_close___Empty
    lambda 11 In_SubscribeC2 = Out_C1_ConnectionClosed_client_close___c2_SubAck
    lambda 11 In_UnSubScribeC2 = Out_C1_ConnectionClosed_client_close___c2_UnSubAck
    lambda 11 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___Empty
    lambda 10 In_ConnectC2 = Out_C1_ConnectionClosed_client_close___c2_ConnAck
    lambda 10 In_ConnectC1WithWill = Out_C1_ConnAck__c2_ConnectionClosed_eof_stream
    lambda 10 In_PublishQoS0C2 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_eof_stream
    lambda 10 In_PublishQoS1C1 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_eof_stream
    lambda 10 In_SubscribeC1 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_eof_stream
    lambda 10 In_UnSubScribeC1 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_eof_stream
    lambda 10 In_SubscribeC2 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_eof_stream
    lambda 10 In_UnSubScribeC2 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_eof_stream
    lambda 10 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_eof_stream
    lambda 9 In_ConnectC2 = Out_Empty__c2_ConnectionClosed_eof_stream
    lambda 9 In_ConnectC1WithWill = Out_C1_ConnectionClosed_eof_stream___Pub_c2_my_topic_bye
    lambda 9 In_PublishQoS0C2 = Out_Empty__Pub_c2_my_topic_messageQos0
    lambda 9 In_PublishQoS1C1 = Out_C1_PubAck__Pub_c2_my_topic_messageQos1
    lambda 9 In_SubscribeC1 = Out_C1_SubAck__Pub_c1_my_topic_bye___Empty
    lambda 9 In_UnSubScribeC1 = Out_C1_UnSubAck__Empty
    lambda 9 In_SubscribeC2 = Out_Empty__c2_SubAck
    lambda 9 In_UnSubScribeC2 = Out_Empty__c2_UnSubAck
    lambda 9 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___Pub_c2_my_topic_bye
    lambda 13 In_ConnectC2 = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_eof_stream
    lambda 13 In_ConnectC1WithWill = Out_C1_ConnAck__Empty
    lambda 13 In_PublishQoS0C2 = Out_C1_ConnectionClosed_eof_stream___Pub_c2_my_topic_messageQos0
    lambda 13 In_PublishQoS1C1 = Out_C1_ConnectionClosed_eof_stream___Empty
    lambda 13 In_SubscribeC1 = Out_C1_ConnectionClosed_eof_stream___Empty
    lambda 13 In_UnSubScribeC1 = Out_C1_ConnectionClosed_eof_stream___Empty
    lambda 13 In_SubscribeC2 = Out_C1_ConnectionClosed_eof_stream___c2_SubAck
    lambda 13 In_UnSubScribeC2 = Out_C1_ConnectionClosed_eof_stream___c2_UnSubAck
    lambda 13 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___Empty
    lambda 6 In_ConnectC2 = Out_Empty__c2_ConnAck
    lambda 6 In_ConnectC1WithWill = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_eof_stream
    lambda 6 In_PublishQoS0C2 = Out_Empty__c2_ConnectionClosed_eof_stream
    lambda 6 In_PublishQoS1C1 = Out_C1_PubAck__c2_ConnectionClosed_eof_stream
    lambda 6 In_SubscribeC1 = Out_C1_SubAck__Pub_c1_my_topic_bye___c2_ConnectionClosed_eof_stream
    lambda 6 In_UnSubScribeC1 = Out_C1_UnSubAck__c2_ConnectionClosed_eof_stream
    lambda 6 In_SubscribeC2 = Out_Empty__c2_ConnectionClosed_eof_stream
    lambda 6 In_UnSubScribeC2 = Out_Empty__c2_ConnectionClosed_eof_stream
    lambda 6 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_eof_stream
    lambda 8 In_ConnectC2 = Out_Empty__c2_ConnectionClosed_eof_stream
    lambda 8 In_ConnectC1WithWill = Out_C1_ConnectionClosed_eof_stream___Empty
    lambda 8 In_PublishQoS0C2 = Out_Pub_c1_my_topic_messageQos0___Empty
    lambda 8 In_PublishQoS1C1 = Out_Pub_c1_my_topic_messageQos1___c1_PubAck__Empty
    lambda 8 In_SubscribeC1 = Out_C1_SubAck__Empty
    lambda 8 In_UnSubScribeC1 = Out_C1_UnSubAck__Empty
    lambda 8 In_SubscribeC2 = Out_Empty__c2_SubAck__Pub_c2_my_topic_bye
    lambda 8 In_UnSubScribeC2 = Out_Empty__c2_UnSubAck
    lambda 8 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___Empty
    lambda 12 In_ConnectC2 = Out_C1_ConnectionClosed_eof_stream___c2_ConnAck
    lambda 12 In_ConnectC1WithWill = Out_C1_ConnAck__c2_ConnectionClosed_eof_stream
    lambda 12 In_PublishQoS0C2 = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_eof_stream
    lambda 12 In_PublishQoS1C1 = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_eof_stream
    lambda 12 In_SubscribeC1 = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_eof_stream
    lambda 12 In_UnSubScribeC1 = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_eof_stream
    lambda 12 In_SubscribeC2 = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_eof_stream
    lambda 12 In_UnSubScribeC2 = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_eof_stream
    lambda 12 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_eof_stream
    lambda 14 In_ConnectC2 = Out_Empty__c2_ConnectionClosed_eof_stream
    lambda 14 In_ConnectC1WithWill = Out_C1_ConnectionClosed_eof_stream___Pub_c2_my_topic_bye
    lambda 14 In_PublishQoS0C2 = Out_Pub_c1_my_topic_messageQos0___Pub_c2_my_topic_messageQos0
    lambda 14 In_PublishQoS1C1 = Out_Pub_c1_my_topic_messageQos1___c1_PubAck__Pub_c2_my_topic_messageQos1
    lambda 14 In_SubscribeC1 = Out_C1_SubAck__Empty
    lambda 14 In_UnSubScribeC1 = Out_C1_UnSubAck__Empty
    lambda 14 In_SubscribeC2 = Out_Empty__c2_SubAck
    lambda 14 In_UnSubScribeC2 = Out_Empty__c2_UnSubAck
    lambda 14 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___Pub_c2_my_topic_bye
    lambda 15 In_ConnectC2 = Out_Empty__c2_ConnAck
    lambda 15 In_ConnectC1WithWill = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_eof_stream
    lambda 15 In_PublishQoS0C2 = Out_Empty__c2_ConnectionClosed_eof_stream
    lambda 15 In_PublishQoS1C1 = Out_Pub_c1_my_topic_messageQos1___c1_PubAck__c2_ConnectionClosed_eof_stream
    lambda 15 In_SubscribeC1 = Out_C1_SubAck__c2_ConnectionClosed_eof_stream
    lambda 15 In_UnSubScribeC1 = Out_C1_UnSubAck__c2_ConnectionClosed_eof_stream
    lambda 15 In_SubscribeC2 = Out_Empty__c2_ConnectionClosed_eof_stream
    lambda 15 In_UnSubScribeC2 = Out_Empty__c2_ConnectionClosed_eof_stream
    lambda 15 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_eof_stream
    lambda 5 In_ConnectC2 = Out_Empty__c2_ConnAck
    lambda 5 In_ConnectC1WithWill = Out_C1_ConnectionClosed_eof_stream___c2_ConnectionClosed_client_close
    lambda 5 In_PublishQoS0C2 = Out_Empty__c2_ConnectionClosed_client_close
    lambda 5 In_PublishQoS1C1 = Out_Pub_c1_my_topic_messageQos1___c1_PubAck__c2_ConnectionClosed_client_close
    lambda 5 In_SubscribeC1 = Out_C1_SubAck__c2_ConnectionClosed_client_close
    lambda 5 In_UnSubScribeC1 = Out_C1_UnSubAck__c2_ConnectionClosed_client_close
    lambda 5 In_SubscribeC2 = Out_Empty__c2_ConnectionClosed_client_close
    lambda 5 In_UnSubScribeC2 = Out_Empty__c2_ConnectionClosed_client_close
    lambda 5 In_DisconnectTCPC1 = Out_C1_ConnectionClosed_client_close___c2_ConnectionClosed_client_close
    lambda _ _ = error "haal-gen: undefined transition"
