-- Generated by haal-gen. Do not edit manually.
module Haal.Models.MQTT.HbmqttNonClean
    ( HbmqttNonCleanInput (..)
    , HbmqttNonCleanOutput (..)
    , hbmqttNonClean
    ) where

import qualified Data.Set as Set
import Haal.Automaton.MealyAutomaton (MealyAutomaton, mkMealyAutomaton)

data HbmqttNonCleanInput
    = In_ConnectC2
    | In_ConnectC1
    | In_PublishQoS1C1
    | In_SubscribeC2QoS1
    | In_UnSubscribeC2
    | In_DisconnectC2
    deriving (Show, Eq, Ord, Enum, Bounded)

data HbmqttNonCleanOutput
    = Out_C1_ConnectionClosed__c2_ConnAck
    | Out_C1_ConnAck__c2_ConnectionClosed
    | Out_C1_ConnectionClosed__c2_ConnectionClosed
    | Out_Empty__c2_ConnAck
    | Out_Empty__c2_ConnectionClosed
    | Out_C1_PubAck__c2_ConnectionClosed
    | Out_Empty__Empty
    | Out_C1_PubAck__Empty
    | Out_Empty__c2_SubAck
    | Out_Empty__c2_UnSubAck
    | Out_C1_ConnectionClosed__Empty
    | Out_C1_ConnAck__Empty
    | Out_C1_ConnectionClosed__c2_SubAck
    | Out_C1_ConnectionClosed__c2_UnSubAck
    | Out_C1_PubAck__c2_Pub_my_topic_messageQos1_1
    | Out_Empty__c2_Pub_my_topic_messageQos1_1___c2_ConnAck
    | Out_Empty__c2_Pub_my_topic_messageQos1_1___c2_Pub_my_topic_messageQos1_1___c2_ConnAck
    deriving (Show, Eq, Ord, Enum, Bounded)

hbmqttNonClean :: MealyAutomaton Int HbmqttNonCleanInput HbmqttNonCleanOutput
hbmqttNonClean = mkMealyAutomaton delta lambda (Set.fromList [0..9]) 0
  where
    delta 0 In_ConnectC2 = 1
    delta 0 In_ConnectC1 = 2
    delta 0 In_PublishQoS1C1 = 0
    delta 0 In_SubscribeC2QoS1 = 0
    delta 0 In_UnSubscribeC2 = 0
    delta 0 In_DisconnectC2 = 0
    delta 2 In_ConnectC2 = 3
    delta 2 In_ConnectC1 = 2
    delta 2 In_PublishQoS1C1 = 2
    delta 2 In_SubscribeC2QoS1 = 2
    delta 2 In_UnSubscribeC2 = 2
    delta 2 In_DisconnectC2 = 2
    delta 3 In_ConnectC2 = 3
    delta 3 In_ConnectC1 = 3
    delta 3 In_PublishQoS1C1 = 3
    delta 3 In_SubscribeC2QoS1 = 4
    delta 3 In_UnSubscribeC2 = 3
    delta 3 In_DisconnectC2 = 2
    delta 1 In_ConnectC2 = 1
    delta 1 In_ConnectC1 = 3
    delta 1 In_PublishQoS1C1 = 1
    delta 1 In_SubscribeC2QoS1 = 5
    delta 1 In_UnSubscribeC2 = 1
    delta 1 In_DisconnectC2 = 0
    delta 4 In_ConnectC2 = 4
    delta 4 In_ConnectC1 = 4
    delta 4 In_PublishQoS1C1 = 4
    delta 4 In_SubscribeC2QoS1 = 4
    delta 4 In_UnSubscribeC2 = 3
    delta 4 In_DisconnectC2 = 6
    delta 6 In_ConnectC2 = 4
    delta 6 In_ConnectC1 = 6
    delta 6 In_PublishQoS1C1 = 7
    delta 6 In_SubscribeC2QoS1 = 6
    delta 6 In_UnSubscribeC2 = 6
    delta 6 In_DisconnectC2 = 6
    delta 7 In_ConnectC2 = 4
    delta 7 In_ConnectC1 = 7
    delta 7 In_PublishQoS1C1 = 8
    delta 7 In_SubscribeC2QoS1 = 7
    delta 7 In_UnSubscribeC2 = 7
    delta 7 In_DisconnectC2 = 7
    delta 8 In_ConnectC2 = 4
    delta 8 In_ConnectC1 = 8
    delta 8 In_PublishQoS1C1 = 8
    delta 8 In_SubscribeC2QoS1 = 8
    delta 8 In_UnSubscribeC2 = 8
    delta 8 In_DisconnectC2 = 8
    delta 5 In_ConnectC2 = 5
    delta 5 In_ConnectC1 = 4
    delta 5 In_PublishQoS1C1 = 5
    delta 5 In_SubscribeC2QoS1 = 5
    delta 5 In_UnSubscribeC2 = 1
    delta 5 In_DisconnectC2 = 9
    delta 9 In_ConnectC2 = 5
    delta 9 In_ConnectC1 = 6
    delta 9 In_PublishQoS1C1 = 9
    delta 9 In_SubscribeC2QoS1 = 9
    delta 9 In_UnSubscribeC2 = 9
    delta 9 In_DisconnectC2 = 9
    delta _ _ = error "haal-gen: undefined transition"
    lambda 0 In_ConnectC2 = Out_C1_ConnectionClosed__c2_ConnAck
    lambda 0 In_ConnectC1 = Out_C1_ConnAck__c2_ConnectionClosed
    lambda 0 In_PublishQoS1C1 = Out_C1_ConnectionClosed__c2_ConnectionClosed
    lambda 0 In_SubscribeC2QoS1 = Out_C1_ConnectionClosed__c2_ConnectionClosed
    lambda 0 In_UnSubscribeC2 = Out_C1_ConnectionClosed__c2_ConnectionClosed
    lambda 0 In_DisconnectC2 = Out_C1_ConnectionClosed__c2_ConnectionClosed
    lambda 2 In_ConnectC2 = Out_Empty__c2_ConnAck
    lambda 2 In_ConnectC1 = Out_Empty__c2_ConnectionClosed
    lambda 2 In_PublishQoS1C1 = Out_C1_PubAck__c2_ConnectionClosed
    lambda 2 In_SubscribeC2QoS1 = Out_Empty__c2_ConnectionClosed
    lambda 2 In_UnSubscribeC2 = Out_Empty__c2_ConnectionClosed
    lambda 2 In_DisconnectC2 = Out_Empty__c2_ConnectionClosed
    lambda 3 In_ConnectC2 = Out_Empty__Empty
    lambda 3 In_ConnectC1 = Out_Empty__Empty
    lambda 3 In_PublishQoS1C1 = Out_C1_PubAck__Empty
    lambda 3 In_SubscribeC2QoS1 = Out_Empty__c2_SubAck
    lambda 3 In_UnSubscribeC2 = Out_Empty__c2_UnSubAck
    lambda 3 In_DisconnectC2 = Out_Empty__c2_ConnectionClosed
    lambda 1 In_ConnectC2 = Out_C1_ConnectionClosed__Empty
    lambda 1 In_ConnectC1 = Out_C1_ConnAck__Empty
    lambda 1 In_PublishQoS1C1 = Out_C1_ConnectionClosed__Empty
    lambda 1 In_SubscribeC2QoS1 = Out_C1_ConnectionClosed__c2_SubAck
    lambda 1 In_UnSubscribeC2 = Out_C1_ConnectionClosed__c2_UnSubAck
    lambda 1 In_DisconnectC2 = Out_C1_ConnectionClosed__c2_ConnectionClosed
    lambda 4 In_ConnectC2 = Out_Empty__Empty
    lambda 4 In_ConnectC1 = Out_Empty__Empty
    lambda 4 In_PublishQoS1C1 = Out_C1_PubAck__c2_Pub_my_topic_messageQos1_1
    lambda 4 In_SubscribeC2QoS1 = Out_Empty__c2_SubAck
    lambda 4 In_UnSubscribeC2 = Out_Empty__c2_UnSubAck
    lambda 4 In_DisconnectC2 = Out_Empty__c2_ConnectionClosed
    lambda 6 In_ConnectC2 = Out_Empty__c2_ConnAck
    lambda 6 In_ConnectC1 = Out_Empty__c2_ConnectionClosed
    lambda 6 In_PublishQoS1C1 = Out_C1_PubAck__c2_ConnectionClosed
    lambda 6 In_SubscribeC2QoS1 = Out_Empty__c2_ConnectionClosed
    lambda 6 In_UnSubscribeC2 = Out_Empty__c2_ConnectionClosed
    lambda 6 In_DisconnectC2 = Out_Empty__c2_ConnectionClosed
    lambda 7 In_ConnectC2 = Out_Empty__c2_Pub_my_topic_messageQos1_1___c2_ConnAck
    lambda 7 In_ConnectC1 = Out_Empty__c2_ConnectionClosed
    lambda 7 In_PublishQoS1C1 = Out_C1_PubAck__c2_ConnectionClosed
    lambda 7 In_SubscribeC2QoS1 = Out_Empty__c2_ConnectionClosed
    lambda 7 In_UnSubscribeC2 = Out_Empty__c2_ConnectionClosed
    lambda 7 In_DisconnectC2 = Out_Empty__c2_ConnectionClosed
    lambda 8 In_ConnectC2 = Out_Empty__c2_Pub_my_topic_messageQos1_1___c2_Pub_my_topic_messageQos1_1___c2_ConnAck
    lambda 8 In_ConnectC1 = Out_Empty__c2_ConnectionClosed
    lambda 8 In_PublishQoS1C1 = Out_C1_PubAck__c2_ConnectionClosed
    lambda 8 In_SubscribeC2QoS1 = Out_Empty__c2_ConnectionClosed
    lambda 8 In_UnSubscribeC2 = Out_Empty__c2_ConnectionClosed
    lambda 8 In_DisconnectC2 = Out_Empty__c2_ConnectionClosed
    lambda 5 In_ConnectC2 = Out_C1_ConnectionClosed__Empty
    lambda 5 In_ConnectC1 = Out_C1_ConnAck__Empty
    lambda 5 In_PublishQoS1C1 = Out_C1_ConnectionClosed__Empty
    lambda 5 In_SubscribeC2QoS1 = Out_C1_ConnectionClosed__c2_SubAck
    lambda 5 In_UnSubscribeC2 = Out_C1_ConnectionClosed__c2_UnSubAck
    lambda 5 In_DisconnectC2 = Out_C1_ConnectionClosed__c2_ConnectionClosed
    lambda 9 In_ConnectC2 = Out_C1_ConnectionClosed__c2_ConnAck
    lambda 9 In_ConnectC1 = Out_C1_ConnAck__c2_ConnectionClosed
    lambda 9 In_PublishQoS1C1 = Out_C1_ConnectionClosed__c2_ConnectionClosed
    lambda 9 In_SubscribeC2QoS1 = Out_C1_ConnectionClosed__c2_ConnectionClosed
    lambda 9 In_UnSubscribeC2 = Out_C1_ConnectionClosed__c2_ConnectionClosed
    lambda 9 In_DisconnectC2 = Out_C1_ConnectionClosed__c2_ConnectionClosed
    lambda _ _ = error "haal-gen: undefined transition"
